// frontend/src/pages/Playlist/Edit.vue
<script setup>
import { $t } from '@/i18n.js';
import { defineAsyncComponent, ref, watch, reactive, onMounted } from 'vue';
import { useForm } from '@/helpers/useForm'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { BFormCheckbox, BFormInput, BFormTextarea } from 'bootstrap-vue-next';
import { removeEmptyObjectsKeys } from '@/Services/FormService.js';
const UserLayout = defineAsyncComponent(() => import('@/Layouts/UserLayout.vue'));
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
const Multiselect = defineAsyncComponent(() => import('@vueform/multiselect'));
import '@vueform/multiselect/themes/default.css';
import route from "@/helpers/route"

const playlist = ref(null);
const loading = ref(true);
const currentRoute = useRoute();

  onMounted(async () => {
    try {
      const response = await apiClient.get(`/playlists/${currentRoute.params.uuid}/edit`);
      const apiData = response.data;
      playlist.value = apiData.playlist ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const defaultArtworkLink = '/assets/images/playlist.png';

const artworkPreview = ref(playlist.value?.artwork);
const artworkSelected = ref(false);

const authStore = useAuthStore();
const user = authStore.user;
const genres = ref(authStore.filter_presets.genres);

const form = useForm({
    _method: 'patch',
    artwork: null,
    genres: playlist.value?.genres,
    title: playlist.value?.title,
    description: playlist.value?.description,
    is_visible: playlist.value?.is_visible,
    allow_comments: playlist.value?.allow_comments,
    is_explicit: playlist.value?.is_explicit,
});

const resetArtwork = () => {
    form.reset('artwork');
};

const setArtwork = (e) => {
    form.artwork = e.target.files[0];
};

const setImagePreview = (image) => {
    artworkPreview.value = URL.createObjectURL(image);
    artworkSelected.value = true;
};

const submit = () => {
    form.transform(removeEmptyObjectsKeys).post(route('playlists.update', playlist.value), {
        preserveState: true,
        preserveScroll: true,
        onSuccess: () => {
            form.reset();
        },
    });
};

watch(
    () => form.artwork,
    (newValue) => {
        if (newValue) {
            setImagePreview(newValue);
        } else {
            artworkPreview.value = defaultArtworkLink;
            artworkSelected.value = false;
        }
    },
);
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <UserLayout :user="playlist.user">
        <div class="d-flex flex-column gap-3">
            <div class="row gy-3">
                <div
                    class="col-12 col-lg-4 d-flex flex-column gap-4 justify-content-center justify-content-xl-start align-items-center"
                >
                    <img :src="artworkPreview" :alt="playlist.title" class="img-fluid rounded-4 border-pink" />
                    <DefaultButton v-if="artworkSelected" class-list="btn-outline" @click="resetArtwork">
                        <Icon :icon="['fas', 'trash']" />
                        {{ $t('buttons.clear') }}
                    </DefaultButton>
                    <label class="btn-default btn-pink">
                        {{ $t('misc.artwork') }}
                        <input class="d-none" accept="image/*" type="file" @change="setArtwork" />
                    </label>
                </div>
                <div class="col">
                    <div class="d-flex flex-column justify-content-start align-items-center gap-4">
                        <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label class="font-default fs-14 color-text">{{ $t('misc.title') }}</label>
                            <BFormInput maxlength="175" v-model="form.title" required />
                        </div>
                        <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label class="font-default fs-14 color-text">
                                {{ $t('misc.genres') }}
                            </label>
                            <Multiselect
                                :options="genres"
                                v-model="form.genres"
                                :searchable="true"
                                :multiple="true"
                                mode="tags"
                                label="text"
                                track-by="value"
                                clear-on-search
                                hide-selected
                            >
                            </Multiselect>
                        </div>
                        <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label class="font-default fs-14 color-text">
                                {{ $t('misc.description') }}
                            </label>
                            <BFormTextarea maxlength="180" v-model="form.description" />
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div
                        class="d-flex flex-column flex-md-row justify-content-center justify-content-md-between align-items-center flex-wrap"
                    >
                        <div class="d-flex flex-row justify-content-start gap-3">
                            <div class="d-flex align-items-center justify-content-start gap-2">
                                <BFormCheckbox checked="checked" v-model="form.allow_comments" />
                                <label class="font-default fs-14 color-text">{{ $t('misc.allow_comments') }}</label>
                            </div>
                            <div class="d-flex align-items-center justify-content-start gap-2">
                                <BFormCheckbox checked="checked" v-model="form.is_visible" />
                                <label class="font-default fs-14 color-text">{{ $t('misc.make_public') }}</label>
                            </div>
                            <div class="d-flex align-items-center justify-content-start gap-2">
                                <BFormCheckbox checked="checked" v-model="form.is_explicit" />
                                <label class="font-default fs-14 color-text">{{ $t('misc.explicit') }}</label>
                            </div>
                        </div>
                        <div class="d-flex flex-row justify-content-center align-items-center gap-3">
                            <DefaultButton class-list="btn-outline" :href="route('playlists.show', playlist)">
                                {{ $t('buttons.cancel') }}
                            </DefaultButton>
                            <DefaultButton class-list="btn-pink" @click="submit">
                                {{ $t('buttons.save') }}
                            </DefaultButton>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </UserLayout>
</template>
  </template>

<style scoped></style>

// frontend/src/pages/Playlist/Edit.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';
import UserLayout from '@/Layouts/UserLayout';

export default function PlaylistEdit() {
    const { uuid } = useParams<{ uuid: string }>();
    const navigate = useNavigate();
    const [playlist, setPlaylist] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    const [title, setTitle] = useState('');
    const [description, setDescription] = useState('');
    const [isVisible, setIsVisible] = useState(true);
    const [allowComments, setAllowComments] = useState(true);
    const [isExplicit, setIsExplicit] = useState(false);
    const [artworkPreview, setArtworkPreview] = useState<string>('');
    const [artworkFile, setArtworkFile] = useState<File | null>(null);
    const [artworkSelected, setArtworkSelected] = useState(false);
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await apiClient.get(`/playlists/${uuid}/edit`);
                const apiData = response.data;
                const playlistData = apiData.playlist ?? null;
                setPlaylist(playlistData);
                if (playlistData) {
                    setTitle(playlistData.title || '');
                    setDescription(playlistData.description || '');
                    setIsVisible(playlistData.is_visible ?? true);
                    setAllowComments(playlistData.allow_comments ?? true);
                    setIsExplicit(playlistData.is_explicit ?? false);
                    setArtworkPreview(playlistData.artwork || '/assets/images/playlist.png');
                }
            } catch (error) {
                console.error('Failed to load page data:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [uuid]);

    const handleArtworkChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0] || null;
        setArtworkFile(file);
        if (file) {
            setArtworkPreview(URL.createObjectURL(file));
            setArtworkSelected(true);
        } else {
            setArtworkPreview('/assets/images/playlist.png');
            setArtworkSelected(false);
        }
    };

    const resetArtwork = () => {
        setArtworkFile(null);
        setArtworkPreview(playlist?.artwork || '/assets/images/playlist.png');
        setArtworkSelected(false);
    };

    const handleSubmit = async () => {
        if (submitting) return;
        setSubmitting(true);
        try {
            const formData = new FormData();
            formData.append('_method', 'PATCH');
            formData.append('title', title);
            formData.append('description', description);
            formData.append('is_visible', isVisible ? '1' : '0');
            formData.append('allow_comments', allowComments ? '1' : '0');
            formData.append('is_explicit', isExplicit ? '1' : '0');
            if (artworkFile) formData.append('artwork', artworkFile);
            await apiClient.post(`/playlists/${uuid}`, formData);
        } catch (error) {
            console.error('Failed to update playlist:', error);
        } finally {
            setSubmitting(false);
        }
    };

    if (loading) {
        return (
            <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
                <div className="spinner-border text-light" role="status">
                    <span className="visually-hidden">Loading...</span>
                </div>
            </div>
        );
    }

    if (!playlist) return null;

    return (
        <UserLayout user={playlist.user}>
            <div className="d-flex flex-column gap-3">
                <div className="row gy-3">
                    <div className="col-12 col-lg-4 d-flex flex-column gap-4 justify-content-center justify-content-xl-start align-items-center">
                        <img src={artworkPreview} alt={playlist.title} className="img-fluid rounded-4 border-pink" />
                        {artworkSelected && (
                            <button className="btn btn-default btn-outline" onClick={resetArtwork}>
                                <i className="fas fa-trash" /> Clear
                            </button>
                        )}
                        <label className="btn-default btn-pink" style={{ cursor: 'pointer' }}>
                            Artwork
                            <input className="d-none" accept="image/*" type="file" onChange={handleArtworkChange} />
                        </label>
                    </div>
                    <div className="col">
                        <div className="d-flex flex-column justify-content-start align-items-center gap-4">
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                                <label className="font-default fs-14 color-text">Title</label>
                                <input
                                    type="text"
                                    className="form-control"
                                    maxLength={175}
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    required
                                />
                            </div>
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                                <label className="font-default fs-14 color-text">Description</label>
                                <textarea
                                    className="form-control"
                                    maxLength={180}
                                    value={description}
                                    onChange={(e) => setDescription(e.target.value)}
                                />
                            </div>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="d-flex flex-column flex-md-row justify-content-center justify-content-md-between align-items-center flex-wrap">
                            <div className="d-flex flex-row justify-content-start gap-3">
                                <div className="form-check">
                                    <input className="form-check-input" type="checkbox" checked={allowComments} onChange={(e) => setAllowComments(e.target.checked)} />
                                    <label className="form-check-label font-default fs-14 color-text">Allow Comments</label>
                                </div>
                                <div className="form-check">
                                    <input className="form-check-input" type="checkbox" checked={isVisible} onChange={(e) => setIsVisible(e.target.checked)} />
                                    <label className="form-check-label font-default fs-14 color-text">Make Public</label>
                                </div>
                                <div className="form-check">
                                    <input className="form-check-input" type="checkbox" checked={isExplicit} onChange={(e) => setIsExplicit(e.target.checked)} />
                                    <label className="form-check-label font-default fs-14 color-text">Explicit</label>
                                </div>
                            </div>
                            <div className="d-flex flex-row justify-content-center align-items-center gap-3">
                                <Link to={`/playlists/${playlist.uuid}`} className="btn btn-default btn-outline">Cancel</Link>
                                <button className="btn btn-default btn-pink" onClick={handleSubmit} disabled={submitting}>Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </UserLayout>
    );
}
