// frontend/src/pages/User/Following.vue
<script setup>
import { ref, reactive, onMounted, defineAsyncComponent } from 'vue';
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { $t } from '@/i18n.js';
import { isNotEmpty } from '@/Services/MiscService.js';
const FollowerCard = defineAsyncComponent(() => import('@/Components/Cards/FollowerCard.vue'));
const UserLayout = defineAsyncComponent(() => import('@/Layouts/UserLayout.vue'));
import route from "@/helpers/route"

const user = ref(null);
const following = ref(null);
const loading = ref(true);
const currentRoute = useRoute();

  onMounted(async () => {
    try {
      const response = await apiClient.get(`/users/${currentRoute.params.username}/following`);
      const apiData = response.data;
      user.value = apiData.user ?? null;
    following.value = apiData.following ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const unfollow = (user) => {
    const currentUser = useAuthStore().user;

    apiClient.delete(route('users.following.destroy', { user: currentUser.uuid }), {
        data: {
            user_uuid: user.value?.uuid,
        },
        onSuccess: () => {},
        preserveScroll: true,
        preserveState: true,
    });
};
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <UserLayout :title="$t('pages.user.following')" :user="user">
        <div v-if="isNotEmpty(following)" class="row w-100">
            <FollowerCard v-for="user in following" :user="user" @unfollow="unfollow(user)" controllable />
        </div>
        <div v-else class="d-flex flex-column w-100 vh-100 align-items-center justify-content-center text-center">
            {{ $t('pages.user.no_following') }}
        </div>
    </UserLayout>
</template>
  </template>

// frontend/src/pages/User/Following.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import { useAuthStore } from '@/stores/auth';
import apiClient from '@/api/client';
import { USER_PROFILE, FOLLOWING_API } from '@/api/endpoints';
import UserLayout from '@/Layouts/UserLayout';

export default function UserFollowing() {
  const { username } = useParams<{ username: string }>();
  const [user, setUser] = useState<any>(null);
  const [following, setFollowing] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const authUser = useAuthStore((s) => s.user);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get(USER_PROFILE.FOLLOWING(username!));
        const apiData = response.data;
        setUser(apiData.user ?? null);
        setFollowing(apiData.following ?? []);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [username]);

  const handleUnfollow = useCallback(async (targetUser: any) => {
    try {
      await apiClient.delete(FOLLOWING_API.DELETE(targetUser.uuid), {
        data: { user_uuid: targetUser.uuid },
      });
      setFollowing((prev) => prev.filter((u) => u.uuid !== targetUser.uuid));
    } catch (error) {
      console.error('Failed to unfollow:', error);
    }
  }, []);

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <UserLayout title="Following" user={user}>
      {following && following.length > 0 ? (
        <div className="row w-100">
          {following.map((u: any) => (
            <div key={u.uuid} className="follower-card">
              <span>{u.name}</span>
              <button className="btn btn-sm btn-outline-danger" onClick={() => handleUnfollow(u)}>
                Unfollow
              </button>
            </div>
          ))}
        </div>
      ) : (
        <div className="d-flex flex-column w-100 vh-100 align-items-center justify-content-center text-center">
          Not following anyone
        </div>
      )}
    </UserLayout>
  );
}
