// frontend/src/pages/User/Notifications.tsx
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import apiClient from '@/api/client';
import { USER_PROFILE } from '@/api/endpoints';
import UserLayout from '@/Layouts/UserLayout';

export default function UserNotifications() {
  const { username } = useParams<{ username: string }>();
  const [user, setUser] = useState<any>(null);
  const [notifications, setNotifications] = useState<any[]>([]);
  const [recentActivities, setRecentActivities] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState(0);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get(`/users/${username}/notifications`);
        const apiData = response.data;
        setUser(apiData.user ?? null);
        setNotifications(apiData.notifications ?? []);
        setRecentActivities(apiData.recent_activities ?? []);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [username]);

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <UserLayout title="My Notifications" user={user} overflow={false}>
      <div className="tabs-header w-100">
        <ul className="nav tab-item px-4 w-100">
          <li
            className={`nav-item tab-item default-text-color px-4 ${activeTab === 0 ? 'tab-item-active' : ''}`}
            onClick={() => setActiveTab(0)}
            style={{ cursor: 'pointer' }}
          >
            Notifications
          </li>
          <li
            className={`nav-item tab-item default-text-color px-4 ${activeTab === 1 ? 'tab-item-active' : ''}`}
            onClick={() => setActiveTab(1)}
            style={{ cursor: 'pointer' }}
          >
            Recent Actions
          </li>
        </ul>
      </div>
      <div className="py-4">
        {activeTab === 0 && (
          notifications.length > 0 ? (
            <div className="d-flex flex-column w-100 vh-100 overflow-y-auto p-1">
              {notifications.map((notification: any, index: number) => (
                <div key={notification.id || index} className="notification-card">
                  {notification.message || notification.data?.message}
                </div>
              ))}
            </div>
          ) : (
            <div className="d-block text-center">No notifications</div>
          )
        )}
        {activeTab === 1 && (
          recentActivities.length > 0 ? (
            <div className="d-flex flex-column w-100 vh-100 overflow-y-auto p-1">
              {recentActivities.map((activity: any, index: number) => (
                <div key={activity.id || index} className="notification-card">
                  {activity.message || activity.data?.message}
                </div>
              ))}
            </div>
          ) : (
            <div className="d-block text-center">No recent actions</div>
          )
        )}
      </div>
    </UserLayout>
  );
}

// frontend/src/pages/User/Notifications.vue
<script setup>
import { ref, reactive, onMounted, defineAsyncComponent } from 'vue';
import { useRoute } from 'vue-router'
import apiClient from '@/api/client'
import { $t } from '@/i18n.js';
import { BTab, BTabs } from 'bootstrap-vue-next';
import { isNotEmpty } from '@/Services/MiscService.js';
const UserLayout = defineAsyncComponent(() => import('@/Layouts/UserLayout.vue'));
const NotificationFullCard = defineAsyncComponent(() => import('@/Components/Cards/NotificationFullCard.vue'));

const user = ref(null);
const notifications = ref(null);
const recent_activities = ref(null);
const loading = ref(true);
const currentRoute = useRoute();

  onMounted(async () => {
    try {
      const response = await apiClient.get(`/users/${currentRoute.params.username}/notifications`);
      const apiData = response.data;
      user.value = apiData.user ?? null;
    notifications.value = apiData.notifications ?? null;
    recent_activities.value = apiData.recent_activities ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <UserLayout :title="$t('pages.user.notifications.my_notifications')" :user="user" :overflow="false">
        <BTabs
            nav-wrapper-class="tabs-header w-100"
            nav-class="tab-item px-4 w-100"
            active-nav-item-class="tab-item-active"
            nav-item-class="tab-item default-text-color px-4"
            tab-class="py-4"
            fill
        >
            <BTab :title="$t('pages.user.notifications.title')">
                <div v-if="isNotEmpty(notifications)" class="d-flex flex-column w-100 vh-100 overflow-y-auto p-1">
                    <NotificationFullCard
                        v-for="notification in notifications"
                        :notification="notification"
                        dark-font
                    />
                </div>
                <div v-else class="d-block text-center">
                    {{ $t('pages.user.notifications.no_notifications') }}
                </div>
            </BTab>
            <BTab :title="$t('pages.user.notifications.recent_actions')">
                <div v-if="isNotEmpty(recent_activities)" class="d-flex flex-column w-100 vh-100 overflow-y-auto p-1">
                    <NotificationFullCard
                        v-for="notification in recent_activities"
                        :notification="notification"
                        dark-font
                    />
                </div>
                <div v-else class="d-block text-center">
                    {{ $t('pages.user.notifications.no_recent_actions') }}
                </div>
            </BTab>
        </BTabs>
    </UserLayout>
</template>
  </template>
