// frontend/src/pages/User/Show.vue
<script setup>
import { ref, reactive, onMounted, computed, defineAsyncComponent } from 'vue';
import { useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { $t } from '@/i18n.js';
import { isNotEmpty } from '@/Services/MiscService.js';
import { addToFavorites, removeFromFavorites } from '@/Services/FavoriteService.js';
const UserLayout = defineAsyncComponent(() => import('@/Layouts/UserLayout.vue'));
const CircledText = defineAsyncComponent(() => import('@/Components/CircledText.vue'));
const Song = defineAsyncComponent(() => import('@/Components/Song.vue'));
const ProfileBlockHeader = defineAsyncComponent(() => import('@/Components/ProfileBlockHeader.vue'));

const user = ref(null);
const recent = ref(null);
const loading = ref(true);
const currentRoute = useRoute();

  onMounted(async () => {
    try {
      const response = await apiClient.get(`/users/${currentRoute.params.username}`);
      const apiData = response.data;
      user.value = apiData.user ?? null;
    recent.value = apiData.recent ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const authStore = useAuthStore();

const pageTitle = computed(() =>
    user.value?.own_profile
        ? $t('pages.user.my_profile_overview')
        : $t('pages.user.user_profile_overview', { name: user.value?.name }),
);
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <UserLayout :title="pageTitle" :user="user" :overflow="false">
        <div class="d-flex flex-row gap-4 justify-content-xl-start justify-content-center align-items-center flex-wrap">
            <CircledText :title="user.favorites" :description="$t('pages.user.favorites')" />
            <CircledText :title="user.total_plays" :description="$t('pages.user.total_plays')" />
            <CircledText :title="user.free_followers_count" :description="$t('pages.user.followers.free')" />
            <CircledText :title="user.patrons_count" :description="$t('pages.user.followers.patrons')" />
        </div>
        <div v-if="isNotEmpty(recent)" class="d-flex flex-column w-100 mt-4 vh-100">
            <ProfileBlockHeader :title="$t('pages.user.recent_tracks')" />
            <div class="d-flex flex-column overflow-y-auto p-2">
                <Song
                    v-for="song in recent"
                    :song="song"
                    :key="song.uuid"
                    :is-owned="user.uuid === song.user.uuid"
                    @add-to-favorites="addToFavorites($event, authStore.user.uuid)"
                    @remove-from-favorites="removeFromFavorites($event, authStore.user.uuid)"
                    dark-font
                    can-view
                />
            </div>
        </div>
    </UserLayout>
</template>
  </template>

// frontend/src/pages/User/Show.tsx
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useAuthStore } from '@/stores/auth';
import apiClient from '@/api/client';
import { USER_PROFILE } from '@/api/endpoints';
import UserLayout from '@/Layouts/UserLayout';

export default function UserShow() {
  const { username } = useParams<{ username: string }>();
  const [user, setUser] = useState<any>(null);
  const [recent, setRecent] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const authUser = useAuthStore((s) => s.user);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get(USER_PROFILE.SHOW(username!));
        const apiData = response.data;
        setUser(apiData.user ?? null);
        setRecent(apiData.recent ?? []);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [username]);

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  const pageTitle = user?.own_profile
    ? 'My Profile Overview'
    : `${user?.name}'s Profile Overview`;

  return (
    <UserLayout title={pageTitle} user={user} overflow={false}>
      <div className="d-flex flex-row gap-4 justify-content-xl-start justify-content-center align-items-center flex-wrap">
        <div className="circled-text">
          <div className="circled-text__title">{user?.favorites}</div>
          <div className="circled-text__description">Favorites</div>
        </div>
        <div className="circled-text">
          <div className="circled-text__title">{user?.total_plays}</div>
          <div className="circled-text__description">Total Plays</div>
        </div>
        <div className="circled-text">
          <div className="circled-text__title">{user?.free_followers_count}</div>
          <div className="circled-text__description">Free Followers</div>
        </div>
        <div className="circled-text">
          <div className="circled-text__title">{user?.patrons_count}</div>
          <div className="circled-text__description">Patrons</div>
        </div>
      </div>
      {recent && recent.length > 0 && (
        <div className="d-flex flex-column w-100 mt-4 vh-100">
          <div className="profile-block-header">Recent Tracks</div>
          <div className="d-flex flex-column overflow-y-auto p-2">
            {recent.map((song: any) => (
              <div key={song.uuid} className="song-item">
                {song.title}
              </div>
            ))}
          </div>
        </div>
      )}
    </UserLayout>
  );
}
