// frontend/src/Components/Carousels/SlideCarousel.tsx
import React from 'react';
import { SwiperSlide } from 'swiper/react';
import DefaultCarousel from '@/Components/Carousels/DefaultCarousel';

interface SlideCarouselProps {
    items: any[] | Record<string, any>;
}

export default function SlideCarousel({ items = [] }: SlideCarouselProps) {
    const carouselConfig = {
        itemsToShow: 'auto' as const,
        wrapAround: true,
        gap: 24,
    };

    const itemsArray = Array.isArray(items) ? items : Object.values(items);

    return (
        <DefaultCarousel config={carouselConfig}>
            {itemsArray.map((slide: any, i: number) => (
                <SwiperSlide key={i}>
                    <img src={slide.artwork} alt={slide.title} className="img-fluid rounded-4" />
                </SwiperSlide>
            ))}
        </DefaultCarousel>
    );
}

// Afterdarkv2-main/resources/js/Components/Carousels/SlideCarousel.vue
<script setup>
import { Slide, Navigation } from 'vue3-carousel';
import { defineAsyncComponent } from 'vue';
const DefaultCarousel = defineAsyncComponent(() => import('@/Components/Carousels/DefaultCarousel.vue'));
const ImageLink = defineAsyncComponent(() => import('@/Components/Links/ImageLink.vue'));
const RoundButton = defineAsyncComponent(() => import('@/Components/Buttons/RoundButton.vue'));
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
import 'vue3-carousel/carousel.css';

const props = defineProps({
    items: {
        type: Object,
        required: true,
        default: {},
    },
});

const carouselConfig = {
    itemsToShow: 'auto',
    wrapAround: true,
    gap: 24,
};
</script>

<template>
    <DefaultCarousel :config="carouselConfig">
        <template #slides>
            <Slide v-for="(slide, i) in items" :key="i">
                <template #default>
                    <img :src="slide.artwork" :alt="slide.title" class="img-fluid rounded-4" />
                </template>
            </Slide>
        </template>
        <template #navigation>
            <Navigation>
                <template #prev>
                    <RoundButton class-list="btn-white">
                        <Icon :icon="['fas', 'arrow-left']" size="1x" />
                    </RoundButton>
                </template>
                <template #next>
                    <RoundButton class-list="btn-white">
                        <Icon :icon="['fas', 'arrow-right']" size="1x" />
                    </RoundButton>
                </template>
            </Navigation>
        </template>
    </DefaultCarousel>
</template>
