// frontend/src/Components/PlaylistTrack.tsx
import React, { useState, useMemo } from 'react';
import { $t } from '@/i18n';
import { isNotEmpty } from '@/Services/MiscService';
import ObjectTypes from '@/Enums/ObjectTypes';
import Icon from '@/Components/Icons/Icon';
import IconButton from '@/Components/Buttons/IconButton';
import route from '@/helpers/route';

interface PlaylistTrackProps {
    track: {
        uuid: string;
        title: string;
        artwork?: string;
        duration?: string;
        type?: string;
        favorite?: boolean;
        [key: string]: any;
    };
    podcast_uuid?: string | null;
    likeable?: boolean;
    playlists?: any[];
    collaboratedPlaylists?: any[];
    draggable?: boolean;
    controllable?: boolean;
    darkFont?: boolean;
    onLike?: (data: { uuid: string; type: string }) => void;
    onDeleted?: (data: { uuid: string; type: string }) => void;
    onShared?: (track: any) => void;
    onReported?: (track: any) => void;
    onAddToPlaylist?: (data: { playlist_uuid: string; song_uuid: string }) => void;
}

export default function PlaylistTrack({
    track,
    podcast_uuid = null,
    likeable = false,
    playlists = [],
    collaboratedPlaylists = [],
    draggable = false,
    controllable = false,
    darkFont = false,
    onLike,
    onDeleted,
    onShared,
    onReported,
    onAddToPlaylist,
}: PlaylistTrackProps) {
    const [showPlaylistDropdown, setShowPlaylistDropdown] = useState(false);
    const [showOptionsDropdown, setShowOptionsDropdown] = useState(false);

    const hasCollaboratedPlaylists = isNotEmpty(collaboratedPlaylists);
    const hasOwnPlaylists = isNotEmpty(playlists);
    const type = useMemo(() => ObjectTypes.getObjectType(track.type || ''), [track.type]);

    const link = useMemo(
        () => type === ObjectTypes.Song ? route('songs.show', track.uuid) : route('episodes.show', track.uuid),
        [type, track.uuid]
    );

    return (
        <div className="d-flex flex-row w-100 align-items-center justify-content-start gap-3 p-2 module">
            {likeable && (
                <IconButton
                    icon={track.favorite ? 'heart-circle-check' : 'heart'}
                    onClick={() => onLike?.({ uuid: track.uuid, type: ObjectTypes.Song })}
                />
            )}
            <div className="position-relative flex-shrink-0">
                <img className="img-thumb rounded-2" src={track.artwork} alt={track.title} />
            </div>
            <div className="text-truncate">
                <a className="color-text font-default flex-nowrap text-decoration-none" href={link}>
                    {track.title}
                </a>
            </div>
            <div className="ms-auto d-flex flex-row gap-3 align-items-center">
                <div className="font-merge fs-12 color-grey">{track.duration}</div>
                {likeable && (hasOwnPlaylists || hasCollaboratedPlaylists) && (
                    <div className="dropdown">
                        <button className="btn-default p-2 btn-icon" onClick={() => setShowPlaylistDropdown(!showPlaylistDropdown)}>
                            <Icon icon={['fas', 'file-circle-plus']} />
                        </button>
                        {showPlaylistDropdown && (
                            <div className="dropdown-menu show">
                                {hasOwnPlaylists && (
                                    <>
                                        <h6 className="dropdown-header">{$t('misc.my_playlists')}</h6>
                                        {playlists.map((playlist: any) => (
                                            <button key={playlist.uuid} className="dropdown-item" onClick={() => { onAddToPlaylist?.({ playlist_uuid: playlist.uuid, song_uuid: track.uuid }); setShowPlaylistDropdown(false); }}>
                                                {playlist.title}
                                            </button>
                                        ))}
                                    </>
                                )}
                                {hasCollaboratedPlaylists && (
                                    <>
                                        <h6 className="dropdown-header">{$t('misc.collaborated_playlists')}</h6>
                                        {collaboratedPlaylists.map((playlist: any) => (
                                            <button key={playlist.uuid} className="dropdown-item" onClick={() => { onAddToPlaylist?.({ playlist_uuid: playlist.uuid, song_uuid: track.uuid }); setShowPlaylistDropdown(false); }}>
                                                {playlist.title}
                                            </button>
                                        ))}
                                    </>
                                )}
                            </div>
                        )}
                    </div>
                )}
                {likeable && (
                    <div className="dropdown">
                        <button className="btn-default p-2 btn-icon" onClick={() => setShowOptionsDropdown(!showOptionsDropdown)}>
                            <Icon icon={['fas', 'ellipsis-vertical']} />
                        </button>
                        {showOptionsDropdown && (
                            <div className="dropdown-menu show">
                                <h6 className="dropdown-header">{track.title}</h6>
                                <button className="dropdown-item font-merge" onClick={() => { onShared?.(track); setShowOptionsDropdown(false); }}>
                                    {$t('pages.playlist.menus.share')}
                                </button>
                                <button className="dropdown-item font-merge" onClick={() => { onReported?.(track); setShowOptionsDropdown(false); }}>
                                    {$t('pages.playlist.menus.report')}
                                </button>
                                {controllable && !podcast_uuid && (
                                    <button className="dropdown-item font-merge" onClick={() => { onDeleted?.({ uuid: track.uuid, type }); setShowOptionsDropdown(false); }}>
                                        {$t('pages.playlist.menus.remove_from_playlist')}
                                    </button>
                                )}
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}

// Afterdarkv2-main/resources/js/Components/PlaylistTrack.vue
<script setup>
import { $t } from '@/i18n.js';
import { BDropdown, BDropdownHeader, BDropdownItem, BDropdownItemButton } from 'bootstrap-vue-next';
import { computed, defineAsyncComponent } from 'vue';
import ObjectTypes from '@/Enums/ObjectTypes.js';
import { isNotEmpty } from '@/Services/MiscService.js';
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const IconButton = defineAsyncComponent(() => import('@/Components/Buttons/IconButton.vue'));

const props = defineProps({
    track: {
        type: Object,
        required: true,
    },
    podcast_uuid: {
        type: String,
        default: null,
    },
    likeable: {
        type: Boolean,
        default: false,
    },
    playlists: {
        type: Array,
        default: [],
    },
    collaboratedPlaylists: {
        type: Array,
        default: [],
    },
    draggable: {
        type: Boolean,
        default: false,
    },
    controllable: {
        type: Boolean,
        default: false,
    },
    darkFont: {
        type: Boolean,
        default: false,
    },
});

const emit = defineEmits(['like', 'deleted', 'shared', 'reported', 'add-to-playlist']);

const hasCollaboratedPlaylists = computed(() => isNotEmpty(props.collaboratedPlaylists));
const hasOwnPlaylists = computed(() => isNotEmpty(props.playlists));
const type = computed(() => ObjectTypes.getObjectType(props.track.type));

const link = computed(() =>
    type.value === ObjectTypes.Song ? route('songs.show', props.track.uuid) : route('episodes.show', props.track.uuid),
);
</script>

<template>
    <div class="d-flex flex-row w-100 align-items-center justify-content-start gap-3 p-2 module">
        <!--    @if(isset($sortable) && $sortable)-->
        <!--    <div class="drag-handle btn-icon-only color-text d-none d-sm-flex">-->
        <!--      <svg width="18" height="18" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">-->
        <!--        &lt;!&ndash;!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.&ndash;&gt;-->
        <!--        <path d="M32 288c-17.7 0-32 14.3-32 32s14.3 32 32 32l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L32 288zm0-128c-17.7 0-32 14.3-32 32s14.3 32 32 32l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L32 160z"/>-->
        <!--      </svg>-->
        <!--    </div>-->
        <!--    @endif-->
        <IconButton
            v-if="likeable"
            :icon="track.favorite ? 'heart-circle-check' : 'heart'"
            @click="$emit('like', { uuid: track.uuid, type: ObjectTypes.Song })"
        />
        <div class="position-relative flex-shrink-0">
            <img class="img-thumb rounded-2" :src="track.artwork" :alt="track.title" />
        </div>
        <div class="text-truncate">
            <a class="color-text font-default flex-nowrap text-decoration-none" :href="link">
                {{ track.title }}
            </a>
        </div>
        <div class="ms-auto d-flex flex-row gap-3 align-items-center">
            <div class="font-merge fs-12 color-grey">{{ track.duration }}</div>
            <BDropdown
                v-if="likeable && (hasOwnPlaylists || hasCollaboratedPlaylists)"
                no-wrapper
                no-caret
                toggle-class="btn-default p-2 btn-icon"
            >
                <template #button-content>
                    <Icon :icon="['fas', 'file-circle-plus']" />
                </template>
                <template v-if="hasOwnPlaylists">
                    <BDropdownHeader>
                        {{ $t('misc.my_playlists') }}
                    </BDropdownHeader>
                    <BDropdownItemButton
                        v-for="playlist in playlists"
                        :key="playlist.uuid"
                        @click="
                            $emit('add-to-playlist', {
                                playlist_uuid: playlist.uuid,
                                song_uuid: track.uuid,
                            })
                        "
                    >
                        {{ playlist.title }}
                    </BDropdownItemButton>
                </template>
                <template v-if="hasCollaboratedPlaylists">
                    <BDropdownHeader>
                        {{ $t('misc.collaborated_playlists') }}
                    </BDropdownHeader>
                    <BDropdownItemButton
                        v-for="playlist in collaboratedPlaylists"
                        :key="playlist.uuid"
                        @click="
                            $emit('add-to-playlist', {
                                playlist_uuid: playlist.uuid,
                                song_uuid: track.uuid,
                            })
                        "
                    >
                        {{ playlist.title }}
                    </BDropdownItemButton>
                </template>
            </BDropdown>
            <BDropdown v-if="likeable" no-caret no-wrapper toggle-class="btn-default p-2 btn-icon">
                <template #button-content>
                    <Icon :icon="['fas', 'ellipsis-vertical']" />
                </template>
                <BDropdownHeader>
                    {{ track.title }}
                </BDropdownHeader>
                <BDropdownItem link-class="font-merge" @click="$emit('shared', track)">
                    {{ $t('pages.playlist.menus.share') }}
                </BDropdownItem>
                <BDropdownItem link-class="font-merge" @click="$emit('reported', track)">
                    {{ $t('pages.playlist.menus.report') }}
                </BDropdownItem>
                <BDropdownItem
                    v-if="controllable & !podcast_uuid"
                    link-class="font-merge"
                    @click="$emit('deleted', { uuid: track.uuid, type: type })"
                >
                    {{ $t('pages.playlist.menus.remove_from_playlist') }}
                </BDropdownItem>
            </BDropdown>
        </div>
    </div>
</template>
