// frontend/src/Components/Song.tsx
import React, { useState, useMemo } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useAudioPlayerStore } from '@/stores/track';
import { useAuthStore } from '@/stores/auth';
import { $t } from '@/i18n';
import { isNotEmpty } from '@/Services/MiscService';
import ObjectTypes from '@/Enums/ObjectTypes';
import route from '@/helpers/route';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import Icon from '@/Components/Icons/Icon';

interface SongProps {
    song: {
        uuid: string;
        path: string;
        title: string;
        streamable: boolean;
        artwork?: string;
        duration?: string;
        is_patron?: boolean;
        is_liked?: boolean;
        allow_download?: boolean;
        type?: string;
        tags?: { tag: string }[];
        user?: { uuid: string; name: string };
        [key: string]: any;
    };
    canView?: boolean;
    darkFont?: boolean;
    is_owned?: boolean;
    onAddToFavorites?: (data: { uuid: string; type: string }) => void;
    onRemoveFromFavorites?: (data: { uuid: string; type: string }) => void;
    onAddToPlaylist?: (data: { playlist_uuid: string; song_uuid: string }) => void;
}

export default function Song({ song, canView = false, darkFont = false, is_owned = false, onAddToFavorites, onRemoveFromFavorites, onAddToPlaylist }: SongProps) {
    const [isHover, setIsHover] = useState(false);
    const [showPlaylistDropdown, setShowPlaylistDropdown] = useState(false);
    const [showOptionsDropdown, setShowOptionsDropdown] = useState(false);

    const audioPlayer = useAudioPlayerStore();
    const { isPlaying, currentTrack, error: playerError } = audioPlayer;
    const user = useAuthStore((s) => s.user);
    const isLogged = useAuthStore((s) => s.isLogged);

    const playlists = user?.playlists || [];
    const collaboratedPlaylists = user?.approvedCollaboratedPlaylists || [];

    const isCurrentTrack = currentTrack?.uuid === song.uuid;
    const canDownload = is_owned || song.allow_download;
    const tags = useMemo(() => song.tags?.slice(0, 4) || [], [song.tags]);
    const hasCollaboratedPlaylists = collaboratedPlaylists.length > 0;
    const hasOwnPlaylists = playlists.length > 0;
    const type = useMemo(() => ObjectTypes.getObjectType(song.type || ''), [song.type]);

    const handlePlayClick = () => {
        try {
            if (isCurrentTrack) {
                audioPlayer.togglePlayPause();
            } else {
                audioPlayer.setTracks(song);
            }
        } catch (error) {
            console.error('Failed to play track:', error);
        }
    };

    const textColorClass = darkFont ? 'default-text-color' : 'color-light';

    return (
        <div
            className={`track no-wrap${isCurrentTrack ? ' border border-danger-subtle' : ''}${playerError && isCurrentTrack ? ' error' : ''}`}
            onMouseOver={() => setIsHover(true)}
            onMouseLeave={() => setIsHover(false)}
        >
            <div className="col-8 order-first col-lg-5 d-flex flex-row align-items-center gap-1 gap-lg-3">
                <div className="d-block">
                    <button className="btn-play-track" onClick={handlePlayClick} disabled={!song.streamable && !isLogged}>
                        <Icon
                            className={!isPlaying || !isCurrentTrack ? 'ms-1' : ''}
                            icon={['fas', isPlaying && isCurrentTrack ? 'pause' : 'play']}
                            size="2x"
                        />
                    </button>
                    {playerError && isCurrentTrack && (
                        <span className="text-danger small d-block mt-1">{playerError}</span>
                    )}
                </div>
                <div className="position-relative d-none d-lg-inline-block">
                    {song.is_patron && (
                        <Icon icon="star" classList="position-absolute top-0 start-100 translate-middle color-yellow" />
                    )}
                    <Icon icon="play" classList="position-absolute top-100 start-100 translate-middle color-yellow" />
                    <img alt={song.title} src={song.artwork} className="track-image rounded-4 d-md-block d-none" />
                </div>
                <div className="d-flex flex-column justify-content-center align-items-start text-truncate">
                    <a className={`title font-default link ${textColorClass}`} href={route('songs.show', song.uuid)}>
                        {song.title}
                    </a>
                    <div className={`description ${textColorClass}`}>
                        <div className="d-none d-md-block">
                            <span>by </span>
                            {canView ? (
                                <a href={route('users.show', song.user?.uuid)} className={`link ${textColorClass}`} title={song.user?.name}>
                                    {song.user?.name ?? ''}
                                </a>
                            ) : (
                                <div className="link">{song.user?.name ?? ''}</div>
                            )}
                        </div>
                        <div className="d-block d-md-none">
                            <span>by {song.user?.name}</span>
                        </div>
                    </div>
                </div>
            </div>
            {isNotEmpty(song.tags) && (
                <div className="d-none d-lg-flex col flex-row flex-wrap justify-content-center align-items-center gap-2">
                    {tags.map((tag: any, i: number) => (
                        <DefaultButton key={i} classList="btn-narrow btn-pink">
                            {tag.tag}
                        </DefaultButton>
                    ))}
                </div>
            )}
            <div className="col order-lg-last d-flex flex-row justify-content-end align-items-center gap-1 gap-lg-3 ms-auto">
                <span className={`font-merge ${textColorClass}`}>{song.duration}</span>
                {canView && playlists && (
                    <div className="dropdown">
                        <button className="btn-default p-2 btn-icon" onClick={() => setShowPlaylistDropdown(!showPlaylistDropdown)}>
                            <Icon icon={['fas', 'file-circle-plus']} />
                        </button>
                        {showPlaylistDropdown && (
                            <div className="dropdown-menu show">
                                {hasOwnPlaylists && (
                                    <>
                                        <h6 className="dropdown-header">{$t('misc.my_playlists')}</h6>
                                        {playlists.map((playlist: any) => (
                                            <button key={playlist.uuid} className="dropdown-item" onClick={() => { onAddToPlaylist?.({ playlist_uuid: playlist.uuid, song_uuid: song.uuid }); setShowPlaylistDropdown(false); }}>
                                                {playlist.title}
                                            </button>
                                        ))}
                                    </>
                                )}
                                {hasCollaboratedPlaylists && (
                                    <>
                                        <h6 className="dropdown-header">{$t('misc.collaborated_playlists')}</h6>
                                        {collaboratedPlaylists.map((playlist: any) => (
                                            <button key={playlist.uuid} className="dropdown-item" onClick={() => { onAddToPlaylist?.({ playlist_uuid: playlist.uuid, song_uuid: song.uuid }); setShowPlaylistDropdown(false); }}>
                                                {playlist.title}
                                            </button>
                                        ))}
                                    </>
                                )}
                            </div>
                        )}
                    </div>
                )}
                {canView && (
                    <div className="dropdown">
                        <button className="btn-default p-2 btn-icon" onClick={() => setShowOptionsDropdown(!showOptionsDropdown)}>
                            <Icon icon={['fas', 'ellipsis-vertical']} />
                        </button>
                        {showOptionsDropdown && (
                            <div className="dropdown-menu show">
                                {song.is_liked ? (
                                    <button className="dropdown-item" onClick={() => { onRemoveFromFavorites?.({ uuid: song.uuid, type }); setShowOptionsDropdown(false); }}>
                                        {$t('menus.track.remove_from_favorites')}
                                    </button>
                                ) : (
                                    <button className="dropdown-item" onClick={() => { onAddToFavorites?.({ uuid: song.uuid, type }); setShowOptionsDropdown(false); }}>
                                        {$t('menus.track.add_to_favorites')}
                                    </button>
                                )}
                                <button className="dropdown-item" onClick={() => setShowOptionsDropdown(false)}>
                                    {$t('menus.track.share')}
                                </button>
                                <button className="dropdown-item" onClick={() => setShowOptionsDropdown(false)}>
                                    {$t('menus.track.report')}
                                </button>
                                <h6 className="dropdown-header">{$t('menus.track.add_to_queue.title')}</h6>
                                <button className="dropdown-item" onClick={() => { audioPlayer.addToQueueNext(song); setShowOptionsDropdown(false); }}>
                                    {$t('menus.track.add_to_queue.play_next')}
                                </button>
                                <button className="dropdown-item" onClick={() => { audioPlayer.addToQueueNext(song); setShowOptionsDropdown(false); }}>
                                    {$t('menus.track.add_to_queue.play_last')}
                                </button>
                                {is_owned && (
                                    <a className="dropdown-item" href={route('songs.edit', song)}>
                                        {$t('buttons.edit')}
                                    </a>
                                )}
                                {canDownload && (
                                    <button className="dropdown-item" onClick={() => setShowOptionsDropdown(false)}>
                                        {$t('buttons.download')}
                                    </button>
                                )}
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}

// Afterdarkv2-main/resources/js/Components/Song.vue
<script setup>
import { computed, defineAsyncComponent, ref } from 'vue';
import { useAudioPlayerStore } from '@/stores/track.js';
import { storeToRefs } from 'pinia';
import { BDropdown, BDropdownGroup, BDropdownHeader, BDropdownItem, BDropdownItemButton } from 'bootstrap-vue-next';
import { $t } from '@/i18n.js';
import { usePage } from '@inertiajs/vue3';
import { useModal, useVfm } from 'vue-final-modal';
import { isLogged } from '@/Services/AuthService.js';
import ObjectTypes from '@/Enums/ObjectTypes.js';
import { isNotEmpty } from '@/Services/MiscService.js';
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
const ShareModal = defineAsyncComponent(() => import('@/Components/Modals/ShareModal.vue'));
const DownloadModal = defineAsyncComponent(() => import('@/Components/Modals/DownloadModal.vue'));
const LoginModal = defineAsyncComponent(() => import('@/Components/Modals/LoginModal.vue'));
const SubscriptionModal = defineAsyncComponent(() => import('@/Components/Modals/SubscriptionModal.vue'));
const ReportModal = defineAsyncComponent(() => import('@/Components/Modals/ReportModal.vue'));

const audioPlayer = useAudioPlayerStore();
const { isPlaying, currentTrack, error: playerError } = storeToRefs(audioPlayer);

const emit = defineEmits(['add-to-favorites', 'remove-from-favorites', 'add-to-playlist']);

const props = defineProps({
    song: {
        type: Object,
        required: true,
        validator: (value) => {
            return value.uuid && value.path && value.title && value.streamable !== undefined;
        },
    },
    canView: {
        type: Boolean,
        default: false,
    },
    darkFont: {
        type: Boolean,
        default: false,
    },
    is_owned: {
        type: Boolean,
        default: false,
    },
});

const vfm = useVfm();

const user = usePage().props.auth.user;
const playlists = ref(user?.playlists);
const isHover = ref(false);
const collaboratedPlaylists = ref(user?.collaborated_playlists);

const isCurrentTrackPlaying = computed(() => currentTrack && currentTrack.uuid === props.song.uuid);
const canDownload = computed(() => props.is_owned || props.song.allow_download);
const isCurrentTrack = computed(() => currentTrack.value?.uuid === props.song.uuid);
const tags = computed(() => props.song.tags?.slice(0, 4));
const hasCollaboratedPlaylists = computed(() => collaboratedPlaylists.value.length > 0);
const hasOwnPlaylists = computed(() => playlists.value.length > 0);
const type = computed(() => ObjectTypes.getObjectType(props.song.type));

const openShareModal = () =>
    useModal({
        component: ShareModal,
        attrs: {
            title: props.song.title,
            item: props.song,
            onClose() {
                vfm.close('share-modal');
            },
            onConfirm() {
                vfm.close('share-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const openDownloadModal = () =>
    useModal({
        component: DownloadModal,
        attrs: {
            title: props.song.title,
            item: props.song,
            type: type.value,
            onClose() {
                vfm.close('download-modal');
            },
            onConfirm() {
                vfm.close('download-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const openSubscriptionModal = () =>
    useModal({
        component: SubscriptionModal,
        attrs: {
            onClose() {
                vfm.close('subscription-modal');
            },
            onConfirm() {
                vfm.close('subscription-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const openReportModal = () =>
    useModal({
        component: ReportModal,
        attrs: {
            item: props.song,
            type: ObjectTypes.Song,
            onClose() {
                vfm.close('report-modal');
            },
            onConfirm() {
                vfm.close('report-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const handlePlayClick = () => {
    if (props.song.is_patron) {
        openSubscriptionModal();
        return;
    }

    try {
        if (isCurrentTrack.value) {
            audioPlayer.togglePlayPause();
        } else {
            audioPlayer.setTracks(props.song);
        }
    } catch (error) {
        console.error('Failed to play track:', error);
    }
};
</script>

<template>
    <div
        class="track no-wrap"
        :class="{
            'border border-danger-subtle': isCurrentTrack,
            error: playerError && isCurrentTrack,
        }"
        @mouseover="isHover = true"
        @mouseleave="isHover = false"
    >
        <div class="col-8 order-first col-lg-5 d-flex flex-row align-items-center gap-1 gap-lg-3">
            <div class="d-block">
                <button class="btn-play-track" @click="handlePlayClick" :disabled="!song.streamable && !isLogged">
                    <Icon
                        :class="{ 'ms-1': !isPlaying || !isCurrentTrack }"
                        :icon="['fas', isPlaying && isCurrentTrack ? 'pause' : 'play']"
                        size="2xl"
                    />
                </button>
                <span v-if="playerError && isCurrentTrack" class="text-danger small d-block mt-1">
                    {{ playerError }}
                </span>
            </div>
            <div class="position-relative d-none d-lg-inline-block">
                <Icon
                    v-if="song.is_patron"
                    icon="star"
                    class-list="position-absolute top-0 start-100 translate-middle color-yellow"
                />
                <Icon icon="play" class-list="position-absolute top-100 start-100 translate-middle color-yellow" />
                <img :alt="song.title" :src="song.artwork" class="track-image rounded-4 d-md-block d-none" />
            </div>
            <div class="d-flex flex-column justify-content-center align-items-start text-truncate">
                <a
                    class="title font-default link"
                    :class="{
                        'color-light': !darkFont,
                        'default-text-color': darkFont,
                    }"
                    :href="route('songs.show', song.uuid)"
                >
                    {{ song.title }}
                </a>
                <div
                    class="description"
                    :class="{
                        'color-light': !darkFont,
                        'default-text-color': darkFont,
                    }"
                >
                    <div class="d-none d-md-block">
                        <span>by </span>
                        <a
                            v-if="canView"
                            :href="route('users.show', song.user.uuid)"
                            class="link"
                            :class="{
                                'color-light': !darkFont,
                                'default-text-color': darkFont,
                            }"
                            :title="song.user.name"
                        >
                            {{ song.user?.name ?? '' }}
                        </a>
                        <div v-else class="link" @click="console.log('click')">
                            {{ song.user?.name ?? '' }}
                        </div>
                    </div>
                    <div class="d-block d-md-none">
                        <span>by {{ song.user?.name }}</span>
                    </div>
                </div>
            </div>
        </div>
        <div
            v-if="isNotEmpty(song.tags)"
            class="d-none d-lg-flex col flex-row flex-wrap justify-content-center align-items-center gap-2"
        >
            <DefaultButton v-for="tag in tags" class-list="btn-narrow btn-pink">
                {{ tag.tag }}
            </DefaultButton>
        </div>
        <div class="col order-lg-last d-flex flex-row justify-content-end align-items-center gap-1 gap-lg-3 ms-auto">
            <span
                class="font-merge"
                :class="{
                    'color-light': !darkFont,
                    'default-text-color': darkFont,
                }"
            >
                {{ song.duration }}
            </span>
            <BDropdown v-if="canView && playlists" no-wrapper no-caret toggle-class="btn-default p-2 btn-icon">
                <template #button-content>
                    <Icon :icon="['fas', 'file-circle-plus']" />
                </template>
                <template v-if="hasOwnPlaylists">
                    <BDropdownHeader>
                        {{ $t('misc.my_playlists') }}
                    </BDropdownHeader>
                    <BDropdownItemButton
                        v-for="playlist in playlists"
                        :key="playlist.uuid"
                        @click="
                            $emit('add-to-playlist', {
                                playlist_uuid: playlist.uuid,
                                song_uuid: song.uuid,
                            })
                        "
                    >
                        {{ playlist.title }}
                    </BDropdownItemButton>
                </template>
                <template v-if="hasCollaboratedPlaylists">
                    <BDropdownHeader>
                        {{ $t('misc.collaborated_playlists') }}
                    </BDropdownHeader>
                    <BDropdownItemButton
                        v-for="playlist in collaboratedPlaylists"
                        :key="playlist.uuid"
                        @click="
                            $emit('add-to-playlist', {
                                playlist_uuid: playlist.uuid,
                                song_uuid: song.uuid,
                            })
                        "
                    >
                        {{ playlist.title }}
                    </BDropdownItemButton>
                </template>
            </BDropdown>
            <BDropdown v-if="canView" no-wrapper no-caret toggle-class="btn-default p-2 btn-icon">
                <template #button-content>
                    <Icon :icon="['fas', 'ellipsis-vertical']" />
                </template>
                <BDropdownItemButton
                    v-if="song.is_liked"
                    @click="$emit('remove-from-favorites', { uuid: song.uuid, type: type })"
                >
                    {{ $t('menus.track.remove_from_favorites') }}
                </BDropdownItemButton>
                <BDropdownItemButton v-else @click="$emit('add-to-favorites', { uuid: song.uuid, type: type })">
                    {{ $t('menus.track.add_to_favorites') }}
                </BDropdownItemButton>
                <BDropdownItemButton @click="openShareModal">
                    {{ $t('menus.track.share') }}
                </BDropdownItemButton>
                <BDropdownItemButton @click="openReportModal">
                    {{ $t('menus.track.report') }}
                </BDropdownItemButton>
                <BDropdownGroup :header="$t('menus.track.add_to_queue.title')">
                    <BDropdownItemButton @click="audioPlayer.addToQueueNext(song)">
                        {{ $t('menus.track.add_to_queue.play_next') }}
                    </BDropdownItemButton>
                    <BDropdownItemButton @click="audioPlayer.addToQueueEnd(song)">
                        {{ $t('menus.track.add_to_queue.play_last') }}
                    </BDropdownItemButton>
                </BDropdownGroup>
                <BDropdownItem v-if="is_owned" :href="route('songs.edit', song)">
                    {{ $t('buttons.edit') }}
                </BDropdownItem>
                <BDropdownItem v-if="canDownload" @click="openDownloadModal">
                    {{ $t('buttons.download') }}
                </BDropdownItem>
            </BDropdown>
        </div>
    </div>
</template>

<style scoped>
.track.error {
    border-color: var(--bs-danger) !important;
}
</style>
