// frontend/src/pages/Podcast/Edit.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';
import UserLayout from '@/Layouts/UserLayout';

export default function PodcastEdit() {
    const { uuid } = useParams<{ uuid: string }>();
    const navigate = useNavigate();
    const [podcast, setPodcast] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    const [title, setTitle] = useState('');
    const [description, setDescription] = useState('');
    const [isVisible, setIsVisible] = useState(true);
    const [allowComments, setAllowComments] = useState(true);
    const [allowDownload, setAllowDownload] = useState(false);
    const [explicit, setExplicit] = useState(false);
    const [artworkPreview, setArtworkPreview] = useState<string>('');
    const [artworkFile, setArtworkFile] = useState<File | null>(null);
    const [artworkSelected, setArtworkSelected] = useState(false);
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await apiClient.get(`/podcasts/${uuid}/edit`);
                const apiData = response.data;
                const podcastData = apiData.podcast ?? null;
                setPodcast(podcastData);
                if (podcastData) {
                    setTitle(podcastData.title || '');
                    setDescription(podcastData.description || '');
                    setIsVisible(podcastData.is_visible ?? true);
                    setAllowComments(podcastData.allow_comments ?? true);
                    setAllowDownload(podcastData.allow_download ?? false);
                    setExplicit(podcastData.explicit ?? false);
                    setArtworkPreview(podcastData.artwork || '/assets/images/podcast.png');
                }
            } catch (error) {
                console.error('Failed to load page data:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [uuid]);

    const handleArtworkChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0] || null;
        setArtworkFile(file);
        if (file) {
            setArtworkPreview(URL.createObjectURL(file));
            setArtworkSelected(true);
        } else {
            setArtworkPreview('/assets/images/podcast.png');
            setArtworkSelected(false);
        }
    };

    const resetArtwork = () => {
        setArtworkFile(null);
        setArtworkPreview(podcast?.artwork || '/assets/images/podcast.png');
        setArtworkSelected(false);
    };

    const handleSubmit = async () => {
        if (submitting) return;
        setSubmitting(true);
        try {
            const formData = new FormData();
            formData.append('_method', 'PATCH');
            formData.append('title', title);
            formData.append('description', description);
            formData.append('is_visible', isVisible ? '1' : '0');
            formData.append('allow_comments', allowComments ? '1' : '0');
            formData.append('allow_download', allowDownload ? '1' : '0');
            formData.append('explicit', explicit ? '1' : '0');
            if (artworkFile) formData.append('artwork', artworkFile);
            await apiClient.post(`/podcasts/${uuid}`, formData);
        } catch (error) {
            console.error('Failed to update podcast:', error);
        } finally {
            setSubmitting(false);
        }
    };

    if (loading) {
        return (
            <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
                <div className="spinner-border text-light" role="status">
                    <span className="visually-hidden">Loading...</span>
                </div>
            </div>
        );
    }

    if (!podcast) return null;

    return (
        <UserLayout user={podcast.user}>
            <div className="d-flex flex-column gap-3">
                <div className="row gy-3">
                    <div className="col-12 col-lg-4 d-flex flex-column gap-4 justify-content-center justify-content-xl-start align-items-center">
                        <img src={artworkPreview} alt={podcast.title} className="img-fluid rounded-4 border-pink" />
                        {artworkSelected && (
                            <button className="btn btn-default btn-outline" onClick={resetArtwork}>
                                <i className="fas fa-trash" /> Clear
                            </button>
                        )}
                        <label className="btn-default btn-pink" style={{ cursor: 'pointer' }}>
                            Artwork
                            <input className="d-none" accept="image/*" type="file" onChange={handleArtworkChange} />
                        </label>
                    </div>
                    <div className="col d-flex flex-column justify-content-start align-items-center gap-4">
                        <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label className="font-default fs-14 color-text">Title</label>
                            <input type="text" className="form-control" maxLength={175} value={title} onChange={(e) => setTitle(e.target.value)} required />
                        </div>
                        <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label className="font-default fs-14 color-text">Description</label>
                            <textarea className="form-control" maxLength={180} value={description} onChange={(e) => setDescription(e.target.value)} />
                        </div>
                    </div>
                    <div className="col-12 d-flex flex-column gap-3">
                        <div className="d-flex flex-row justify-content-between align-items-center w-100 flex-wrap">
                            <div className="form-check form-switch">
                                <input className="form-check-input" type="checkbox" checked={isVisible} onChange={(e) => setIsVisible(e.target.checked)} />
                                <label className="form-check-label">Make Public</label>
                            </div>
                            <div className="form-check form-switch">
                                <input className="form-check-input" type="checkbox" checked={allowComments} onChange={(e) => setAllowComments(e.target.checked)} />
                                <label className="form-check-label">Allow Comments</label>
                            </div>
                            <div className="form-check form-switch">
                                <input className="form-check-input" type="checkbox" checked={allowDownload} onChange={(e) => setAllowDownload(e.target.checked)} />
                                <label className="form-check-label">Allow Download</label>
                            </div>
                            <div className="form-check form-switch">
                                <input className="form-check-input" type="checkbox" checked={explicit} onChange={(e) => setExplicit(e.target.checked)} />
                                <label className="form-check-label">Explicit</label>
                            </div>
                        </div>
                        <div className="d-flex flex-row justify-content-end align-items-center gap-3 w-100">
                            <Link to={`/podcasts/${podcast.uuid}`} className="btn btn-default btn-outline">Cancel</Link>
                            <button className="btn btn-default btn-pink" onClick={handleSubmit} disabled={submitting}>Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </UserLayout>
    );
}

// frontend/src/pages/Podcast/Edit.vue
<script setup>
import { $t } from '@/i18n.js';
import { defineAsyncComponent, ref, watch, reactive, onMounted } from 'vue';
import { useForm } from '@/helpers/useForm'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { BFormCheckbox, BFormInput, BFormTextarea, BFormSelect } from 'bootstrap-vue-next';
import { removeEmptyObjectsKeys, slugify } from '@/Services/FormService.js';
const UserLayout = defineAsyncComponent(() => import('@/Layouts/UserLayout.vue'));
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
import route from "@/helpers/route"

const podcast = ref(null);
const loading = ref(true);
const currentRoute = useRoute();

  onMounted(async () => {
    try {
      const response = await apiClient.get(`/podcasts/${currentRoute.params.uuid}/edit`);
      const apiData = response.data;
      podcast.value = apiData.podcast ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const defaultArtworkLink = '/assets/images/podcast.png';

const artworkPreview = ref(podcast.value?.artwork);
const artworkSelected = ref(false);

const authStore = useAuthStore();
const user = authStore.user;
const tags = ref(authStore.filter_presets.tags);
const countries = ref(authStore.filter_presets.countries);
const languages = ref(authStore.filter_presets.languages);
const categories = ref(authStore.filter_presets.categories);

const form = useForm({
    _method: 'patch',
    artwork: null,
    tags: podcast.value?.tags ?? [],
    title: podcast.value?.title,
    description: podcast.value?.description,
    is_visible: podcast.value?.is_visible,
    allow_comments: podcast.value?.allow_comments,
    allow_download: podcast.value?.allow_download,
    explicit: podcast.value?.explicit,
    categories: podcast.value?.categories ?? [],
    language_id: podcast.value?.language_id,
    country_id: podcast.value?.country_id,
});

const resetArtwork = () => {
    form.reset('artwork');
};

const setArtwork = (e) => {
    form.artwork = e.target.files[0];
};

const setImagePreview = (image) => {
    artworkPreview.value = URL.createObjectURL(image);
    artworkSelected.value = true;
};

const addTag = (tag) => {
    const newTag = {
        id: -Math.floor(Math.random() * 10000000),
        tag: slugify(tag),
    };

    tags.value.push(newTag);
    form.tags.push(newTag);
};

const submit = () => {
    form.transform(removeEmptyObjectsKeys).post(route('podcasts.update', podcast.value), {
        preserveState: true,
        preserveScroll: true,
        onSuccess: () => {
            form.reset();
        },
    });
};

watch(
    () => form.artwork,
    (newValue) => {
        if (newValue) {
            setImagePreview(newValue);
        } else {
            artworkPreview.value = defaultArtworkLink;
            artworkSelected.value = false;
        }
    },
);
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <UserLayout :user="podcast.user">
        <div class="d-flex flex-column gap-3">
            <div class="row gy-3">
                <div
                    class="col-12 col-lg-4 d-flex flex-column gap-4 justify-content-center justify-content-xl-start align-items-center"
                >
                    <img :src="artworkPreview" :alt="podcast.title" class="img-fluid rounded-4 border-pink" />
                    <DefaultButton v-if="artworkSelected" class-list="btn-outline" @click="resetArtwork">
                        <Icon :icon="['fas', 'trash']" />
                        {{ $t('buttons.clear') }}
                    </DefaultButton>
                    <label class="btn-default btn-pink">
                        {{ $t('misc.artwork') }}
                        <input class="d-none" accept="image/*" type="file" @change="setArtwork" />
                    </label>
                </div>
                <div class="col d-flex flex-column justify-content-start align-items-center gap-4">
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                        <label class="font-default fs-14 color-text">{{ $t('misc.title') }}</label>
                        <BFormInput maxlength="175" v-model="form.title" required />
                    </div>
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                        <label class="font-default fs-14 color-text">
                            {{ $t('misc.tags') }}
                        </label>
                        <vue-multiselect
                            v-model="form.tags"
                            :options="tags"
                            :multiple="true"
                            :taggable="true"
                            track-by="id"
                            label="tag"
                            @tag="addTag"
                        />
                    </div>
                    <!--          <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">-->
                    <!--            <label class="font-default fs-14 color-text">-->
                    <!--              {{ $t('misc.categories') }}-->
                    <!--            </label>-->
                    <!--            <vue-multiselect-->
                    <!--                v-model="form.categories"-->
                    <!--                :options="categories"-->
                    <!--                :multiple="true"-->
                    <!--            />-->
                    <!--          </div>-->
                    <div class="d-flex flex-row justify-content-between align-items-start gap-4 w-100">
                        <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label class="font-default fs-14 color-text">
                                {{ $t('misc.country') }}
                            </label>
                            <BFormSelect v-model="form.country_id" :options="countries"></BFormSelect>
                        </div>
                        <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                            <label class="font-default fs-14 color-text">
                                {{ $t('misc.language') }}
                            </label>
                            <BFormSelect v-model="form.language_id" :options="languages"></BFormSelect>
                        </div>
                    </div>
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                        <label class="font-default fs-14 color-text">
                            {{ $t('misc.description') }}
                        </label>
                        <BFormTextarea maxlength="180" v-model="form.description" />
                    </div>
                </div>
                <div class="col-12 d-flex flex-column gap-3">
                    <div class="d-flex flex-row justify-content-between align-items-center w-100 flex-wrap">
                        <BFormCheckbox v-model="form.is_visible" switch size="lg">
                            {{ $t('misc.make_public') }}
                        </BFormCheckbox>
                        <BFormCheckbox v-model="form.allow_comments" switch size="lg">
                            {{ $t('misc.allow_comments') }}
                        </BFormCheckbox>
                        <BFormCheckbox v-model="form.allow_download" switch size="lg">
                            {{ $t('misc.allow_download') }}
                        </BFormCheckbox>
                        <BFormCheckbox v-model="form.explicit" switch size="lg">
                            {{ $t('misc.explicit') }}
                        </BFormCheckbox>
                    </div>
                    <div class="d-flex flex-row justify-content-end align-items-center gap-3 w-100">
                        <DefaultButton class-list="btn-outline" :href="route('podcasts.show', podcast)">
                            {{ $t('buttons.cancel') }}
                        </DefaultButton>
                        <DefaultButton class-list="btn-pink" @click="submit">
                            {{ $t('buttons.save') }}
                        </DefaultButton>
                    </div>
                </div>
            </div>
        </div>
    </UserLayout>
</template>
  </template>
