// frontend/src/pages/Podcast/Index.vue
<script setup>
import { $t } from '@/i18n.js';
import { BAccordion, BAccordionItem, BFormCheckboxGroup, BOffcanvas } from 'bootstrap-vue-next';
import { defineAsyncComponent, onMounted, ref, reactive } from 'vue';
import { useForm } from '@/helpers/useForm'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { removeEmptyObjectsKeys } from '@/Services/FormService.js';
const ImageCard = defineAsyncComponent(() => import('@/Components/Cards/ImageCard.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const Multiselect = defineAsyncComponent(() => import('@vueform/multiselect'));
import '@vueform/multiselect/themes/default.css';
import route from "@/helpers/route"

const regions = ref(null);
const initialFilters = ref(null);
const loading = ref(true);

  onMounted(async () => {
    try {
      const response = await apiClient.get('/podcasts');
      const apiData = response.data;
      regions.value = apiData.regions ?? null;
    initialFilters.value = apiData.filters ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const authStore = useAuthStore();

const categories = ref(authStore.filter_presets.podcast_categories);
const languages = ref(authStore.filter_presets.languages);
const countries = ref(authStore.filter_presets.countries);
const tags = ref(authStore.filter_presets.tags);

const hasFilters = ref(false);
const showFilters = ref(false);
const isLastPage = ref(false);
const filteredTags = ref(tags);

const podcasts = ref([]);

const form = useForm({
    categories: [],
    languages: [],
    countries: [],
    regions: [],
    tags: [],
});

const setFiltersDrawer = () => {
    showFilters.value = !showFilters.value;
};

const resetFilters = () => {
    form.reset();
    applyFilters();
};

const setFilterValues = (filtersData) => {
    let count = 0;

    if (filtersData.isDirty) {
        hasFilters.value = true;

        for (const value of Object.values(filtersData.data())) {
            if (typeof value === 'number') {
                count += 1;
            } else if (value === null) {
            } else {
                count += value.length;
            }
        }
    } else {
        hasFilters.value = false;
    }
};

const applyFilters = () => {
    apiClient.get(
        route('podcasts.index'),
        {
            ...removeEmptyObjectsKeys(form.data()),
        },
        {
            preserveState: true,
            preserveUrl: true,
            only: ['podcasts', 'pagination', 'filters'],
            onSuccess: (page) => {
                podcasts.value = authStore.podcasts;
                setFilterValues(form);

                isLastPage.value = checkLastPage();
            },
        },
    );
};

const loadMore = () => {
    form.transform(() => removeEmptyObjectsKeys()).get(podcasts.value.links?.next, {
        preserveState: true,
        preserveScroll: true,
        only: ['podcasts', 'pagination'],
        onSuccess: (page) => {
            podcasts.value.data = [...podcasts.value.data, ...authStore.podcasts.data];

            // Update the pagination.value metadata with the new data from the server
            podcasts.value.links = authStore.podcasts.links;
            podcasts.value.meta = authStore.podcasts.meta;

            isLastPage.value = checkLastPage();
        },
    });
};

const checkLastPage = () => podcasts.value.meta?.current_page === podcasts.value.meta?.last_page;

onMounted(() => {
    podcasts.value = authStore.podcasts;

    isLastPage.value = checkLastPage();
});
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    <div class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
        <div class="container">
            <div class="row">
                <div class="col text-start">
                    <div class="d-block">
                        <div class="block-title color-light text-truncate">
                            {{ $t('pages.podcasts.title') }}
                        </div>
                        <div class="block-description color-light">
                            {{ $t('pages.podcasts.description') }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12 col-xl-3 pb-3 pb-xl-0">
                    <DefaultButton class-list="btn-outline d-xl-none" @click="setFiltersDrawer">
                        {{ $t('buttons.filters') }}
                    </DefaultButton>
                    <BOffcanvas v-model="showFilters" responsive="xl" placement="start">
                        <div class="d-flex flex-column w-100 bg-default rounded-5 px-3 py-4 gap-3">
                            <div class="fs-4 font-default">
                                {{ $t('buttons.filters') }}
                            </div>
                            <BAccordion free>
                                <BAccordionItem button-class="gap-2" header-class="border-0">
                                    <template #title>
                                        <Icon :icon="['fas', 'cubes-stacked']" class-list="color-pink" />
                                        <span class="font-default">{{ $t('pages.podcasts.filters.categories') }}</span>
                                    </template>
                                    <template #default>
                                        <BFormCheckboxGroup
                                            :options="categories"
                                            v-model="form.categories"
                                            @change="applyFilters"
                                            stacked
                                        />
                                    </template>
                                </BAccordionItem>
                                <BAccordionItem button-class="gap-2" header-class="border-0">
                                    <template #title>
                                        <Icon :icon="['fas', 'language']" class-list="color-pink" />
                                        <span class="font-default">{{ $t('pages.podcasts.filters.languages') }}</span>
                                    </template>
                                    <template #default>
                                        <BFormCheckboxGroup
                                            :options="languages"
                                            v-model="form.languages"
                                            @change="applyFilters"
                                            stacked
                                        />
                                    </template>
                                </BAccordionItem>
                                <BAccordionItem button-class="gap-2" header-class="border-0">
                                    <template #title>
                                        <Icon :icon="['fas', 'flag']" class-list="color-pink" />
                                        <span class="font-default">{{ $t('pages.podcasts.filters.countries') }}</span>
                                    </template>
                                    <template #default>
                                        <BFormCheckboxGroup
                                            :options="countries"
                                            v-model="form.countries"
                                            @change="applyFilters"
                                            stacked
                                        />
                                    </template>
                                </BAccordionItem>
                                <BAccordionItem button-class="gap-2" header-class="border-0">
                                    <template #title>
                                        <Icon :icon="['fas', 'hashtag']" class-list="color-pink" />
                                        <span class="font-default">{{ $t('pages.discover.filters.tags.name') }}</span>
                                    </template>
                                    <template #default>
                                        <div class="d-flex flex-column gap-2">
                                            <Multiselect
                                                :options="filteredTags"
                                                v-model="form.tags"
                                                :searchable="true"
                                                :multiple="true"
                                                mode="tags"
                                                label="tag"
                                                track-by="tag"
                                                clear-on-search
                                                hide-selected
                                                @change="applyFilters"
                                            >
                                            </Multiselect>
                                        </div>
                                    </template>
                                </BAccordionItem>
                                <BAccordionItem button-class="gap-2" header-class="border-0">
                                    <template #title>
                                        <Icon :icon="['fas', 'globe']" class-list="color-pink" />
                                        <span class="font-default">{{ $t('pages.podcasts.filters.regions') }}</span>
                                    </template>
                                    <template #default>
                                        <BFormCheckboxGroup
                                            :options="regions"
                                            v-model="form.regions"
                                            @change="applyFilters"
                                            stacked
                                        />
                                    </template>
                                </BAccordionItem>
                            </BAccordion>
                            <div v-if="hasFilters" class="d-flex flex-row justify-content-center align-items-center">
                                <DefaultButton class-list="btn-outline" @click="resetFilters">
                                    {{ $t('buttons.cancel') }}
                                </DefaultButton>
                            </div>
                        </div>
                    </BOffcanvas>
                </div>
                <div class="col col-xl-9 flex-column">
                    <div class="d-flex flex-row justify-content-center flex-wrap align-items-center gap-2 gap-lg-4">
                        <ImageCard
                            v-for="podcast in podcasts.data"
                            :model="podcast"
                            :route="route('podcasts.show', podcast.uuid)"
                            :key="podcast.uuid"
                        />
                    </div>
                    <DefaultButton
                        class-list="btn-outline mt-2 mx-auto"
                        @click.prevent="loadMore()"
                        :disabled="isLastPage || form.processing"
                    >
                        {{ $t('buttons.load_more') }}
                    </DefaultButton>
                </div>
            </div>
        </div>
    </div>
</template>
  </template>

// frontend/src/pages/Podcast/Index.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';

export default function PodcastIndex() {
    const [podcasts, setPodcasts] = useState<any[]>([]);
    const [regions, setRegions] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [isLastPage, setIsLastPage] = useState(false);
    const [pagination, setPagination] = useState<any>(null);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await apiClient.get('/podcasts');
                const apiData = response.data;
                setRegions(apiData.regions ?? null);
                setPodcasts(apiData.podcasts?.data ?? apiData.podcasts ?? []);
                setPagination(apiData.pagination ?? null);
                if (apiData.podcasts?.meta) {
                    setIsLastPage(apiData.podcasts.meta.current_page >= apiData.podcasts.meta.last_page);
                }
            } catch (error) {
                console.error('Failed to load page data:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, []);

    const loadMore = async () => {
        if (!pagination || isLastPage) return;
        try {
            const nextPage = (pagination.current_page || 1) + 1;
            const response = await apiClient.get('/podcasts', { params: { page: nextPage } });
            const apiData = response.data;
            const newPodcasts = apiData.podcasts?.data ?? apiData.podcasts ?? [];
            setPodcasts((prev) => [...prev, ...newPodcasts]);
            setPagination(apiData.pagination ?? null);
            if (apiData.podcasts?.meta) {
                setIsLastPage(apiData.podcasts.meta.current_page >= apiData.podcasts.meta.last_page);
            }
        } catch (error) {
            console.error('Failed to load more podcasts:', error);
        }
    };

    if (loading) {
        return (
            <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
                <div className="spinner-border text-light" role="status">
                    <span className="visually-hidden">Loading...</span>
                </div>
            </div>
        );
    }

    return (
        <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
            <div className="container">
                <div className="row">
                    <div className="col text-start">
                        <div className="d-block">
                            <div className="block-title color-light text-truncate">Podcasts</div>
                            <div className="block-description color-light">Browse all podcasts</div>
                        </div>
                    </div>
                </div>
                <div className="row mt-3">
                    <div className="col flex-column">
                        <div className="d-flex flex-row justify-content-center flex-wrap align-items-center gap-2 gap-lg-4">
                            {podcasts.map((podcast: any) => (
                                <Link key={podcast.uuid} to={`/podcasts/${podcast.uuid}`} className="text-decoration-none">
                                    <div className="d-flex flex-column align-items-center gap-2">
                                        <img
                                            src={podcast.artwork || podcast.image}
                                            alt={podcast.title}
                                            className="img-fluid rounded-4"
                                            style={{ width: 180, height: 180, objectFit: 'cover' }}
                                        />
                                        <span className="font-merge text-center color-light">{podcast.title}</span>
                                    </div>
                                </Link>
                            ))}
                        </div>
                        <button
                            className="btn btn-default btn-outline mt-2 mx-auto d-block"
                            onClick={loadMore}
                            disabled={isLastPage}
                        >
                            Load More
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
