// frontend/src/Components/Cards/ImageCard.tsx
import React from 'react';

interface ImageCardProps {
    model?: any;
    route: string;
    title?: string;
}

export default function ImageCard({ model, route: routePath, title }: ImageCardProps) {
    const styleImage = model ? { background: `url(${model.artwork})` } : {};
    const cardTitle = title ?? model?.title ?? '';

    return (
        <a href={routePath} className="hoverable-image" style={styleImage}>
            <div className="hoverable-image-title">
                {cardTitle}
            </div>
        </a>
    );
}

// frontend/src/Components/Cards/ImageCard.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
    model: {
        type: Object,
        required: false,
    },
    route: {
        type: String,
        required: true,
    },
    title: {
        type: String,
        required: false,
    },
});

const styleImage = computed(() => `background: url(${props.model.artwork})`);
const cardTitle = computed(() => props.title ?? props.model.title ?? '');
</script>

<template>
    <a :href="route" class="hoverable-image" :style="styleImage">
        <div class="hoverable-image-title">
            {{ cardTitle }}
        </div>
    </a>
</template>
