// frontend/src/Components/Cards/NotificationFullCard.vue
<script setup>
import { computed, defineAsyncComponent, ref } from 'vue';
import { $t } from '@/i18n.js';
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client';
import Activities from '@/Enums/Activities.js';
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const IconButton = defineAsyncComponent(() => import('@/Components/Buttons/IconButton.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
import route from "@/helpers/route"

const props = defineProps({
    notification: {
        type: Object,
        required: true,
    },
    darkFont: {
        type: Boolean,
        default: false,
    },
});

const user = useAuthStore().user;

const notificationLink = ref(Activities.getLink(props.notification));
const isLink = ref(notificationLink.value.length > 0);
const isCollaborationInvite = computed(() => props.notification.action === Activities.InviteCollaboration);
const isRead = computed(() => props.notification.is_read);

const emit = defineEmits(['read']);

const markAsRead = (follow = false) => {
    apiClient.post(
        route('notifications.read', { notification: props.notification.id }),
        {},
        {
            preserveScroll: true,
            // onSuccess: () => {
            //   if (follow) {
            //     vueRouter.push(notificationLink.value);
            //   }
            // }
        },
    );
};

const submit = (response) => {
    apiClient.post(
        route('playlists.collaborators.response', {
            playlist: props.notification.subject.uuid,
            user: props.notification.user.uuid,
        }),
        {
            collaborator_uuid: user.uuid,
            response: response,
        },
        {
            preserveScroll: true,
            onSuccess: () => {
                markAsRead();
            },
        },
    );
};
</script>

<template>
    <div class="track no-wrap w-100 justify-content-between">
        <div
            class="d-flex flex-row justify-content-start align-items-center gap-3 pe-auto cursor-pointer"
            @click="markAsRead(isLink)"
        >
            <img
                class="track-image rounded-4 d-md-block d-none"
                :alt="notification.user?.name"
                :src="notification.user?.artwork"
            />
            <div
                class="description font-default"
                :class="{
                    'color-light': !darkFont,
                    'default-text-color': darkFont,
                }"
            >
                {{ Activities.getText(notification) }}
            </div>
        </div>
        <div v-if="isCollaborationInvite" class="d-flex flex-column justify-content-between gap-1">
            <DefaultButton class-list="btn-pink btn-narrow" @click="submit(true)">
                {{ $t('buttons.accept') }}
            </DefaultButton>
            <DefaultButton class-list="btn-outline btn-narrow" @click="submit(false)">
                {{ $t('buttons.decline') }}
            </DefaultButton>
        </div>
        <div class="d-flex flex-row justify-content-end align-items-center gap-3">
            <span
                class="font-merge"
                :class="{
                    'color-light': !darkFont,
                    'color-grey': darkFont,
                }"
            >
                <Icon :icon="['fas', 'clock']" /> {{ notification.created_at }}
            </span>
            <IconButton icon="xmark" @click="markAsRead" :disabled="isRead" />
        </div>
    </div>
</template>

// frontend/src/Components/Cards/NotificationFullCard.tsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import IconButton from '@/Components/Buttons/IconButton';
import { $t } from '@/i18n';
import { useAuthStore } from '@/stores/auth';
import apiClient from '@/api/client';
import Activities from '@/Enums/Activities.js';
import route from '@/helpers/route';

interface NotificationFullCardProps {
    notification: any;
    darkFont?: boolean;
    onRead?: (notification: any) => void;
}

export default function NotificationFullCard({ notification, darkFont = false, onRead }: NotificationFullCardProps) {
    const user = useAuthStore((s) => s.user);
    const notificationLink = Activities.getLink(notification);
    const isLink = notificationLink && notificationLink.length > 0;
    const isCollaborationInvite = notification.action === Activities.InviteCollaboration;
    const isRead = notification.is_read;

    const markAsRead = (follow = false) => {
        apiClient.post(
            route('notifications.read', { notification: notification.id }),
            {},
        );
        onRead?.(notification);
    };

    const submit = (response: boolean) => {
        apiClient.post(
            route('playlists.collaborators.response', {
                playlist: notification.subject?.uuid,
                user: notification.user?.uuid,
            }),
            {
                collaborator_uuid: user?.uuid,
                response: response,
            },
        ).then(() => {
            markAsRead();
        });
    };

    return (
        <div className="track no-wrap w-100 justify-content-between">
            <div
                className="d-flex flex-row justify-content-start align-items-center gap-3 pe-auto cursor-pointer"
                onClick={() => markAsRead(!!isLink)}
            >
                <img
                    className="track-image rounded-4 d-md-block d-none"
                    alt={notification.user?.name}
                    src={notification.user?.artwork}
                />
                <div
                    className={`description font-default ${!darkFont ? 'color-light' : 'default-text-color'}`}
                >
                    {Activities.getText(notification)}
                </div>
            </div>
            {isCollaborationInvite && (
                <div className="d-flex flex-column justify-content-between gap-1">
                    <DefaultButton classList="btn-pink btn-narrow" onClick={() => submit(true)}>
                        {$t('buttons.accept')}
                    </DefaultButton>
                    <DefaultButton classList="btn-outline btn-narrow" onClick={() => submit(false)}>
                        {$t('buttons.decline')}
                    </DefaultButton>
                </div>
            )}
            <div className="d-flex flex-row justify-content-end align-items-center gap-3">
                <span className={`font-merge ${!darkFont ? 'color-light' : 'color-grey'}`}>
                    <FontAwesomeIcon icon={['fas', 'clock']} /> {notification.created_at}
                </span>
                <IconButton icon={['fas', 'xmark']} onClick={() => markAsRead()} disabled={isRead} />
            </div>
        </div>
    );
}
