// Afterdarkv2-main/resources/js/Components/Cards/PlaylistSongCard.vue
<script setup>
import { computed, defineAsyncComponent } from 'vue';
import { useAudioPlayerStore } from '@/stores/track.js';
const IconButton = defineAsyncComponent(() => import('@/Components/Buttons/IconButton.vue'));

const audioPlayer = useAudioPlayerStore();
const emit = defineEmits(['deleted']);

const props = defineProps({
    song: {
        type: Object,
        required: true,
    },
});

const trimmedTitle = computed(() => `${props.song.title?.substring(0, 25)}...`);

const deleteFromQueue = () => {
    audioPlayer.deleteFromQueue(props.song.uuid);
    emit('deleted');
};
</script>

<template>
    <div class="d-flex flex-row align-items-center justify-content-start gap-3 p-2 module position-relative w-100">
        <IconButton
            class-list="position-absolute top-0 start-100 translate-middle"
            icon="xmark"
            @click="deleteFromQueue"
        />
        <img class="img-thumb rounded-2" :src="song.artwork" :alt="song.title" />
        <span class="text-truncate color-text font-default flex-nowrap text-decoration-none">
            {{ trimmedTitle }}
        </span>
    </div>
</template>

// frontend/src/Components/Cards/PlaylistSongCard.tsx
import React from 'react';
import IconButton from '@/Components/Buttons/IconButton';
import { useAudioPlayerStore } from '@/stores/track';

interface PlaylistSongCardProps {
    song: any;
    onDeleted?: () => void;
}

export default function PlaylistSongCard({ song, onDeleted }: PlaylistSongCardProps) {
    const deleteFromQueue = useAudioPlayerStore((s) => s.deleteFromQueue);

    const trimmedTitle = `${song.title?.substring(0, 25)}...`;

    const handleDelete = () => {
        deleteFromQueue(song.uuid);
        onDeleted?.();
    };

    return (
        <div className="d-flex flex-row align-items-center justify-content-start gap-3 p-2 module position-relative w-100">
            <IconButton
                classList="position-absolute top-0 start-100 translate-middle"
                icon={['fas', 'xmark']}
                onClick={handleDelete}
            />
            <img className="img-thumb rounded-2" src={song.artwork} alt={song.title} />
            <span className="text-truncate color-text font-default flex-nowrap text-decoration-none">
                {trimmedTitle}
            </span>
        </div>
    );
}
