// frontend/src/Components/Cards/SongCard.tsx
import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useAudioPlayerStore } from '@/stores/track';
import { useAuthStore } from '@/stores/auth';
import { setItemLink } from '@/Services/FormService';

interface SongCardProps {
    track: any;
}

export default function SongCard({ track }: SongCardProps) {
    const { isPlaying, currentTrack, togglePlayPause, setTracks } = useAudioPlayerStore();
    const isLogged = useAuthStore((s) => s.isLogged);
    const [isHover, setIsHover] = useState(false);

    const isCurrentTrack = currentTrack?.uuid === track.uuid;

    const handlePlayClick = () => {
        if (track.is_patron) {
            return;
        }

        try {
            if (isCurrentTrack) {
                togglePlayPause();
            } else {
                setTracks(track);
            }
        } catch (error) {
            console.error('Failed to play track:', error);
        }
    };

    return (
        <div
            className="audio-carousel-item"
            onMouseOver={() => setIsHover(true)}
            onMouseLeave={() => setIsHover(false)}
        >
            <div className="position-relative">
                <div
                    className={`position-absolute top-50 start-50 translate-middle ${isHover ? 'd-block' : 'd-none'}`}
                >
                    <button
                        className="btn-play lg"
                        onClick={handlePlayClick}
                        disabled={!track.streamable && !isLogged}
                    >
                        <FontAwesomeIcon
                            className={!isPlaying || !isCurrentTrack ? 'ms-1' : ''}
                            icon={['fas', isPlaying && isCurrentTrack ? 'pause' : 'play']}
                            size="2x"
                        />
                    </button>
                </div>
                <img src={track.artwork} className="audio-carousel-item__img" alt={track.title} />
            </div>
            <div className="audio-carousel-item__info">
                <a href={setItemLink(track)}>
                    <div className="audio-carousel-item__info__title">
                        {track.title}
                    </div>
                    <div className="audio-carousel-item__info__desc overflow-hidden text-truncate">
                        {track.description}
                    </div>
                </a>
            </div>
        </div>
    );
}

// frontend/src/Components/Cards/SongCard.vue
<script setup>
import { useAudioPlayerStore } from '@/stores/track.js';
import { storeToRefs } from 'pinia';
import { computed, defineAsyncComponent, ref } from 'vue';
import { isLogged } from '@/Services/AuthService.js';
import { useModal, useVfm } from 'vue-final-modal';
import { setItemLink } from '@/Services/FormService.js';
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const SubscriptionModal = defineAsyncComponent(() => import('@/Components/Modals/SubscriptionModal.vue'));

const audioPlayer = useAudioPlayerStore();
const { isPlaying, currentTrack } = storeToRefs(audioPlayer);

const props = defineProps({
    track: {
        type: Object,
        required: true,
    },
});

const vfm = useVfm();
const isHover = ref(false);

const openSubscriptionModal = () =>
    useModal({
        component: SubscriptionModal,
        attrs: {
            onClose() {
                vfm.close('subscription-modal');
            },
            onConfirm() {
                vfm.close('subscription-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const isCurrentTrackPlaying = computed(() => currentTrack && currentTrack.uuid === props.track.uuid);

const isCurrentTrack = computed(() => currentTrack.value?.uuid === props.track.uuid);

const handlePlayClick = () => {
    if (props.track.is_patron) {
        openSubscriptionModal();
        return;
    }

    try {
        if (isCurrentTrack.value) {
            audioPlayer.togglePlayPause();
        } else {
            audioPlayer.setTracks(props.track);
        }
    } catch (error) {
        console.error('Failed to play track:', error);
    }
};
</script>

<template>
    <div class="audio-carousel-item" @mouseover="isHover = true" @mouseleave="isHover = false">
        <div class="position-relative">
            <div
                class="position-absolute top-50 start-50 translate-middle"
                :class="{
                    'd-none': !isHover,
                    'd-block': isHover,
                }"
            >
                <button class="btn-play lg" @click="handlePlayClick" :disabled="!track.streamable && !isLogged">
                    <Icon
                        :class="{ 'ms-1': !isPlaying || !isCurrentTrack }"
                        :icon="['fas', isPlaying && isCurrentTrack ? 'pause' : 'play']"
                        size="2xl"
                    />
                </button>
            </div>
            <img :src="track.artwork" class="audio-carousel-item__img" :alt="track.title" />
        </div>
        <div class="audio-carousel-item__info">
            <a :href="setItemLink(track)">
                <div class="audio-carousel-item__info__title">
                    {{ track.title }}
                </div>
                <div class="audio-carousel-item__info__desc overflow-hidden text-truncate">
                    {{ track.description }}
                </div>
            </a>
        </div>
    </div>
</template>
