// frontend/src/Layouts/AppLayout.tsx
import React, { useEffect, useState, lazy, Suspense } from 'react';
import { useLocation } from 'react-router-dom';
import { useAudioPlayerStore } from '@/stores/track';
import { useAuthStore } from '@/stores/auth';

const Header = lazy(() => import('@/Layouts/Components/Header'));
const Footer = lazy(() => import('@/Layouts/Components/Footer'));
const Player = lazy(() => import('@/Components/Player/Player'));
const AdultOnlyModal = lazy(() => import('@/Components/Modals/AdultOnlyModal'));
const AdventureBranchSelectModal = lazy(() => import('@/Components/Modals/AdventureBranchSelectModal'));

interface AppLayoutProps {
    children: React.ReactNode;
}

export default function AppLayout({ children }: AppLayoutProps) {
    const location = useLocation();
    const audioPlayer = useAudioPlayerStore();
    const isAdult = useAuthStore((s) => s.isAdult);
    const authLoaded = useAuthStore((s) => s.authLoaded);
    const [adultDismissed, setAdultDismissed] = useState(false);

    const showAdultModal = !adultDismissed && authLoaded && !isAdult;

    useEffect(() => {
        if (audioPlayer.currentTrack && !audioPlayer.audio) {
            audioPlayer.initializeAudio();
        }
    }, []);

    useEffect(() => {
        if (audioPlayer.isPlaying && !audioPlayer.audio) {
            audioPlayer.initializeAudio();
        }
    }, [location.pathname]);

    const setTrack = (track: any) => {
        audioPlayer.setTracks(track);
        audioPlayer.setShowAdventureModal(false);
    };

    return (
        <div className="d-flex flex-column min-vh-100">
            <Suspense fallback={null}>
                <Header />
            </Suspense>
            <div className="app-main flex-column">
                <div className="d-flex flex-column">
                    {children}
                </div>
            </div>
            <Suspense fallback={null}>
                <Player />
            </Suspense>
            <Suspense fallback={null}>
                <Footer />
            </Suspense>
            <Suspense fallback={null}>
                {showAdultModal && (
                    <AdultOnlyModal
                        show={showAdultModal}
                        onClose={() => setAdultDismissed(true)}
                        onAccepted={() => setAdultDismissed(true)}
                    />
                )}
                {audioPlayer.showAdventureModal && (
                    <AdventureBranchSelectModal
                        show={audioPlayer.showAdventureModal}
                        adventure={audioPlayer.currentTrack}
                        onClose={() => audioPlayer.setShowAdventureModal(false)}
                        onSelected={setTrack}
                    />
                )}
            </Suspense>
        </div>
    );
}

// frontend/src/Layouts/AppLayout.vue
<script setup>
import { defineAsyncComponent, onMounted, ref, watch } from 'vue';
import { ModalsContainer, useVfm } from 'vue-final-modal';
import { toast } from 'vue3-toastify';
import { storeToRefs } from 'pinia';
import { useAudioPlayerStore } from '@/stores/track.js';
import { useAuthStore } from '@/stores/auth';
import { useRoute } from 'vue-router';
const Header = defineAsyncComponent(() => import('@/Layouts/Components/Header.vue'));
const Footer = defineAsyncComponent(() => import('@/Layouts/Components/Footer.vue'));
const AdultOnlyModal = defineAsyncComponent(() => import('@/Components/Modals/AdultOnlyModal.vue'));
const Player = defineAsyncComponent(() => import('@/Components/Player/Player.vue'));
const Persistent = defineAsyncComponent(() => import('@/Components/Layout/Persistent.vue'));
const AdventureBranchSelectModal = defineAsyncComponent(
    () => import('@/Components/Modals/AdventureBranchSelectModal.vue'),
);

const audioPlayer = useAudioPlayerStore();
const { showAdventureModal, currentTrack } = storeToRefs(audioPlayer);

const props = defineProps({
    title: {
        type: String,
        required: false,
    },
});

const authStore = useAuthStore();
const vfm = useVfm();
const currentRoute = useRoute();
const showAdultOnlyModal = ref(false);

const showToast = (text, type) => {
    toast(text, {
        position: 'bottom-left',
        type: type,
        transition: toast.TRANSITIONS.SLIDE,
    });
};

const setTrack = (track) => {
    audioPlayer.setTracks(track);
    showAdventureModal.value = false;
};

watch(
    () => currentRoute.fullPath,
    () => {
        if (audioPlayer.isPlaying && !audioPlayer.audio) {
            audioPlayer.initializeAudio();
        }
    },
);

watch(
    () => props.title,
    (newVal) => {
        if (newVal) {
            document.title = newVal;
        }
    },
    { immediate: true },
);

onMounted(() => {
    if (audioPlayer.currentTrack && !audioPlayer.audio) {
        audioPlayer.initializeAudio();
    }

    showAdultOnlyModal.value = !authStore.isAdult;
});
</script>

<template>
    <div class="d-flex flex-column min-vh-100">
        <Header />
        <div class="app-main flex-column">
            <div class="d-flex flex-column">
                <slot />
            </div>
        </div>
        <Persistent>
            <Player />
        </Persistent>
        <Footer />
    </div>
    <AdultOnlyModal v-model="showAdultOnlyModal" @accepted="vfm.close('adult-only-modal')" />
    <AdventureBranchSelectModal v-model="showAdventureModal" :adventure="currentTrack" @selected="setTrack" />
    <ModalsContainer />
</template>
