// frontend/src/Layouts/SettingsLayout.tsx
import React from 'react';
import SettingsPageMenu from '@/Components/Sections/SettingsPageMenu';

interface SettingsLayoutProps {
    title: string;
    children: React.ReactNode;
}

export default function SettingsLayout({ title, children }: SettingsLayoutProps) {
    return (
        <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
            <div className="container">
                <div className="row">
                    <div className="col-12 col-xl-3 pb-3 pb-xl-0">
                        <SettingsPageMenu />
                    </div>
                    <div className="col col-xl-9">
                        <div className="d-flex flex-column w-100 gap-4 bg-default rounded-5 p-3 p-lg-5">
                            <div className="font-default fs-4">{title}</div>
                            <div className="container-fluid overflow-x-hidden">{children}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// frontend/src/Layouts/SettingsLayout.vue
<script setup>
import { defineAsyncComponent } from 'vue';
const SettingsPageMenu = defineAsyncComponent(() => import('@/Components/Sections/SettingsPageMenu.vue'));

const props = defineProps({
    title: {
        type: String,
        required: true,
    },
});
</script>

<template>
    <div class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
        <div class="container">
            <div class="row">
                <div class="col-12 col-xl-3 pb-3 pb-xl-0">
                    <SettingsPageMenu />
                </div>
                <div class="col col-xl-9">
                    <div class="d-flex flex-column w-100 gap-4 bg-default rounded-5 p-3 p-lg-5">
                        <div class="font-default fs-4">
                            {{ title }}
                        </div>
                        <div class="container-fluid overflow-x-hidden">
                            <slot></slot>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
