// frontend/src/Components/Sections/BlogPageFilters.tsx
import React, { useState, useMemo } from 'react';
import { $t } from '@/i18n';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import Icon from '@/Components/Icons/Icon';

interface BlogPageFiltersProps {
    categories?: { id: number; name: string }[];
    archives?: { created_at: string; count: number; date: string }[];
    tags?: string[];
    filters: {
        categories?: number[];
        dates?: string[];
        tags?: string[];
    };
    onUpdated?: (filters: any) => void;
}

export default function BlogPageFilters({ categories = [], archives = [], tags = [], filters: initialFilters, onUpdated }: BlogPageFiltersProps) {
    const [showFilters, setShowFilters] = useState(false);
    const [selectedCategories, setSelectedCategories] = useState<number[]>(initialFilters.categories ?? []);
    const [selectedDates, setSelectedDates] = useState<string[]>(initialFilters.dates ?? []);
    const [selectedTags, setSelectedTags] = useState<string[]>(initialFilters.tags ?? []);
    const [tagSearch, setTagSearch] = useState('');

    const hasFilters = selectedCategories.length > 0 || selectedDates.length > 0 || selectedTags.length > 0;
    const numberFilters = selectedCategories.length + selectedDates.length + selectedTags.length;

    const handleCategoryChange = (id: number, checked: boolean) => {
        const updated = checked ? [...selectedCategories, id] : selectedCategories.filter((c) => c !== id);
        setSelectedCategories(updated);
        onUpdated?.({ categories: updated, dates: selectedDates, tags: selectedTags });
    };

    const handleDateChange = (date: string, checked: boolean) => {
        const updated = checked ? [...selectedDates, date] : selectedDates.filter((d) => d !== date);
        setSelectedDates(updated);
        onUpdated?.({ categories: selectedCategories, dates: updated, tags: selectedTags });
    };

    const handleTagChange = (tag: string, checked: boolean) => {
        const updated = checked ? [...selectedTags, tag] : selectedTags.filter((t) => t !== tag);
        setSelectedTags(updated);
        onUpdated?.({ categories: selectedCategories, dates: selectedDates, tags: updated });
    };

    const resetFilters = () => {
        setSelectedCategories([]);
        setSelectedDates([]);
        setSelectedTags([]);
        onUpdated?.({ categories: [], dates: [], tags: [] });
    };

    return (
        <>
            <DefaultButton classList="btn-outline d-xl-none" onClick={() => setShowFilters(!showFilters)}>
                {$t('buttons.filters')}
            </DefaultButton>
            <div className={`d-flex flex-column w-100 bg-default rounded-5 px-3 py-4 gap-3 ${showFilters ? '' : 'd-none d-xl-flex'}`}>
                <div className="fs-4 font-default">{$t('buttons.filters')}</div>
                <div className="accordion">
                    <div className="accordion-item border-0">
                        <h2 className="accordion-header">
                            <button className="accordion-button gap-2" type="button" data-bs-toggle="collapse" data-bs-target="#filterCategories">
                                <Icon icon={['fas', 'layer-group']} classList="color-pink" />
                                <span className="font-default">{$t('pages.blog.filters.categories')}</span>
                            </button>
                        </h2>
                        <div id="filterCategories" className="accordion-collapse collapse show">
                            <div className="accordion-body">
                                {categories.map((cat) => (
                                    <div key={cat.id} className="form-check">
                                        <input
                                            className="form-check-input"
                                            type="checkbox"
                                            id={`cat-${cat.id}`}
                                            checked={selectedCategories.includes(cat.id)}
                                            onChange={(e) => handleCategoryChange(cat.id, e.target.checked)}
                                        />
                                        <label className="form-check-label" htmlFor={`cat-${cat.id}`}>{cat.name}</label>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                    <div className="accordion-item border-0">
                        <h2 className="accordion-header">
                            <button className="accordion-button gap-2" type="button" data-bs-toggle="collapse" data-bs-target="#filterArchives">
                                <Icon icon={['fas', 'folder-tree']} classList="color-pink" />
                                <span className="font-default">{$t('pages.blog.filters.archives')}</span>
                            </button>
                        </h2>
                        <div id="filterArchives" className="accordion-collapse collapse show">
                            <div className="accordion-body">
                                {archives.map((archive) => (
                                    <div key={archive.created_at} className="form-check">
                                        <input
                                            className="form-check-input"
                                            type="checkbox"
                                            id={`archive-${archive.created_at}`}
                                            checked={selectedDates.includes(archive.created_at)}
                                            onChange={(e) => handleDateChange(archive.created_at, e.target.checked)}
                                        />
                                        <label className="form-check-label" htmlFor={`archive-${archive.created_at}`}>
                                            ({archive.count}) {archive.date}
                                        </label>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                    <div className="accordion-item border-0">
                        <h2 className="accordion-header">
                            <button className="accordion-button gap-2" type="button" data-bs-toggle="collapse" data-bs-target="#filterTags">
                                <Icon icon={['fas', 'hashtag']} classList="color-pink" />
                                <span className="font-default">{$t('pages.discover.filters.tags.name')}</span>
                            </button>
                        </h2>
                        <div id="filterTags" className="accordion-collapse collapse show">
                            <div className="accordion-body d-flex flex-column gap-2">
                                <input
                                    type="search"
                                    className="form-control"
                                    placeholder={$t('pages.discover.filters.tags.placeholder')}
                                    value={tagSearch}
                                    onChange={(e) => setTagSearch(e.target.value)}
                                />
                                {tags.map((tag) => (
                                    <div key={tag} className="form-check">
                                        <input
                                            className="form-check-input"
                                            type="checkbox"
                                            id={`tag-${tag}`}
                                            checked={selectedTags.includes(tag)}
                                            onChange={(e) => handleTagChange(tag, e.target.checked)}
                                        />
                                        <label className="form-check-label" htmlFor={`tag-${tag}`}>{tag}</label>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
                {hasFilters && (
                    <div className="d-flex flex-column justify-content-between align-items-center gap-3">
                        <div className="store-filter-mobile-count">
                            <span className="total-filter">{numberFilters}</span> {$t('misc.filters_selected')}
                        </div>
                        <div className="d-flex flex-row gap-3 justify-content-center align-items-center">
                            <DefaultButton classList="btn-outline" onClick={resetFilters}>
                                {$t('buttons.cancel')}
                            </DefaultButton>
                        </div>
                    </div>
                )}
            </div>
        </>
    );
}

// frontend/src/Components/Sections/BlogPageFilters.vue
<script setup>
import { $t } from '@/i18n.js';
import { computed, defineAsyncComponent, ref, watch, reactive } from 'vue';
import { useForm } from '@/helpers/useForm'
import { BAccordion, BAccordionItem, BFormCheckboxGroup, BFormInput, BOffcanvas } from 'bootstrap-vue-next';
import apiClient from '@/api/client'
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));

const props = defineProps({
    categories: {
        type: Array,
        default: [],
    },
    archives: {
        type: Array,
        default: [],
    },
    tags: {
        type: Array,
        default: [],
    },
    filters: {
        type: Object,
        required: true,
    },
});

const emit = defineEmits(['updated']);

const hasFilters = ref(false);
const numberFilters = ref(0);
const showFilters = ref(false);

const filters = useForm({
    categories: props.filters.categories ?? [],
    dates: props.filters.dates ?? [],
    tags: props.filters.tags ?? [],
});

const setFiltersDrawer = () => {
    showFilters.value = !showFilters.value;
};

const categoriesOptions = computed(() =>
    props.categories.map((element) => {
        return {
            value: element.id,
            text: element.name,
        };
    }),
);

const archivesOptions = computed(() =>
    props.archives.map((element) => {
        return {
            value: element.created_at,
            text: `(${element.count}) ${element.date}`,
        };
    }),
);

const resetFilters = () => {
    filters.reset();
};

const setFilterValues = (filterValues) => {
    let count = 0;

    if (filterValues.isDirty) {
        for (const value of Object.values(filterValues.data())) {
            if (value.length) {
                hasFilters.value = true;
            }

            count += value.length;
        }
    } else {
        hasFilters.value = false;
    }

    numberFilters.value = count;
};

watch(filters, (newValue) => {
    setFilterValues(newValue);
});
</script>

<template>
    <DefaultButton class-list="btn-outline d-xl-none" @click="setFiltersDrawer">
        {{ $t('buttons.filters') }}
    </DefaultButton>
    <BOffcanvas v-model="showFilters" responsive="xl" placement="start">
        <div class="d-flex flex-column w-100 bg-default rounded-5 px-3 py-4 gap-3">
            <div class="fs-4 font-default">
                {{ $t('buttons.filters') }}
            </div>
            <BAccordion free>
                <BAccordionItem button-class="gap-2" header-class="border-0">
                    <template #title>
                        <Icon :icon="['fas', 'layer-group']" class-list="color-pink" />
                        <span class="font-default">{{ $t('pages.blog.filters.categories') }}</span>
                    </template>
                    <template #default>
                        <BFormCheckboxGroup
                            :options="categoriesOptions"
                            v-model="filters.categories"
                            stacked
                            @update:model-value="$emit('updated', filters)"
                        />
                    </template>
                </BAccordionItem>
                <BAccordionItem button-class="gap-2" header-class="border-0">
                    <template #title>
                        <Icon :icon="['fas', 'folder-tree']" class-list="color-pink" />
                        <span class="font-default">{{ $t('pages.blog.filters.archives') }}</span>
                    </template>
                    <template #default>
                        <BFormCheckboxGroup
                            :options="archivesOptions"
                            v-model="filters.dates"
                            stacked
                            @update:model-value="$emit('updated', filters)"
                        />
                    </template>
                </BAccordionItem>
                <BAccordionItem button-class="gap-2" header-class="border-0">
                    <template #title>
                        <Icon :icon="['fas', 'hashtag']" class-list="color-pink" />
                        <span class="font-default">{{ $t('pages.discover.filters.tags.name') }}</span>
                    </template>
                    <template #default>
                        <div class="d-flex flex-column gap-2">
                            <BFormInput type="search" :placeholder="$t('pages.discover.filters.tags.placeholder')" />
                            <BFormCheckboxGroup
                                :options="tags"
                                v-model="filters.tags"
                                @update:model-value="$emit('updated', filters)"
                            />
                        </div>
                    </template>
                </BAccordionItem>
            </BAccordion>
            <div v-if="hasFilters" class="d-flex flex-column justify-content-between align-items-center gap-3">
                <div class="store-filter-mobile-count">
                    <span class="total-filter">{{ numberFilters }}</span>
                    {{ $t('misc.filters_selected') }}
                </div>
                <div class="d-flex flex-row gap-3 justify-content-center align-items-center">
                    <DefaultButton class-list="btn-outline" @click="resetFilters">
                        {{ $t('buttons.cancel') }}
                    </DefaultButton>
                </div>
            </div>
        </div>
    </BOffcanvas>
</template>

<style scoped></style>
