// frontend/src/pages/Settings/Password.vue
<script setup>
import { ref, reactive, onMounted, computed, defineAsyncComponent } from 'vue';
import { useForm } from '@/helpers/useForm'
import { useRoute } from 'vue-router'
import apiClient from '@/api/client'
import { $t } from '@/i18n.js';
import { BFormInput } from 'bootstrap-vue-next';
const SettingsLayout = defineAsyncComponent(() => import('@/Layouts/SettingsLayout.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
import route from "@/helpers/route"

const form = useForm({
    current_password: '',
    password: '',
    password_confirmation: '',
});

const minimalLength = 8;

const allFieldsSet = ref(false);

const passwordInput = ref(null);
const currentPasswordInput = ref(null);

const updatePassword = () => {
    form.put(route('settings.password.update'), {
        preserveScroll: true,
        preserveState: true,
        onSuccess: () => form.reset(),
        onError: (errors) => {
            if (errors.password) {
                form.reset('password', 'password_confirmation');
                if (passwordInput.value instanceof HTMLInputElement) {
                    passwordInput.value.focus();
                }
            }

            if (errors.current_password) {
                form.reset('current_password');
                if (currentPasswordInput.value instanceof HTMLInputElement) {
                    currentPasswordInput.value.focus();
                }
            }
        },
    });
};

const validateForm = () => {
    if (!form.isDirty) {
        allFieldsSet.value = false;
    } else if (form.password && form.current_password && form.password_confirmation) {
        allFieldsSet.value = true;
    }
};

const validatePwdInput = computed(() => form.password.length > minimalLength);
const validatePwdConfirmInput = computed(() => form.password_confirmation.length > minimalLength);
</script>

<template>
    
    <SettingsLayout :title="$t('menus.user_settings.password')">
        <div class="d-flex flex-column justify-content-start align-items-center gap-4">
            <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                <label class="text-start font-default fs-14 default-text-color">
                    {{ $t('pages.settings.current_password') }}
                </label>
                <BFormInput type="password" v-model="form.current_password" @update:model-value="validateForm" />
            </div>
            <div class="d-flex flex-row justify-content-between align-items-center gap-4 w-100">
                <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                    <label class="text-start font-default fs-14 default-text-color">
                        {{ $t('pages.settings.new_password') }}
                    </label>
                    <BFormInput
                        type="password"
                        v-model="form.password"
                        @update:model-value="validateForm"
                        :state="validatePwdInput"
                    />
                </div>
                <div class="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
                    <label class="text-start font-default fs-14 default-text-color">
                        {{ $t('pages.settings.retype_new_password') }}
                    </label>
                    <BFormInput
                        type="password"
                        v-model="form.password_confirmation"
                        @update:model-value="validateForm"
                        :state="validatePwdConfirmInput"
                    />
                </div>
            </div>
            <span class="fs-12 font-merge color-grey text-center">
                {{ $t('pages.settings.password_description', { count: minimalLength }) }}
            </span>
            <DefaultButton @click="updatePassword" class-list="btn-pink" :disabled="!allFieldsSet">
                {{ $t('buttons.change_password') }}
            </DefaultButton>
        </div>
    </SettingsLayout>
</template>

// frontend/src/pages/Settings/Password.tsx
import React, { useState, useMemo } from 'react';
import apiClient from '@/api/client';
import { SETTINGS } from '@/api/endpoints';
import SettingsLayout from '@/Layouts/SettingsLayout';

export default function SettingsPassword() {
  const [currentPassword, setCurrentPassword] = useState('');
  const [password, setPassword] = useState('');
  const [passwordConfirmation, setPasswordConfirmation] = useState('');

  const minimalLength = 8;

  const allFieldsSet = currentPassword.length > 0 && password.length > 0 && passwordConfirmation.length > 0;
  const validatePwdInput = password.length > minimalLength;
  const validatePwdConfirmInput = passwordConfirmation.length > minimalLength;

  const handleUpdatePassword = async () => {
    try {
      await apiClient.put(SETTINGS.PASSWORD, {
        current_password: currentPassword,
        password,
        password_confirmation: passwordConfirmation,
      });
      setCurrentPassword('');
      setPassword('');
      setPasswordConfirmation('');
    } catch (error) {
      console.error('Failed to update password:', error);
    }
  };

  return (
    <SettingsLayout title="Password">
      <div className="d-flex flex-column justify-content-start align-items-center gap-4">
        <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
          <label className="text-start font-default fs-14 default-text-color">
            Current Password
          </label>
          <input
            type="password"
            className="form-control"
            value={currentPassword}
            onChange={(e) => setCurrentPassword(e.target.value)}
          />
        </div>
        <div className="d-flex flex-row justify-content-between align-items-center gap-4 w-100">
          <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
            <label className="text-start font-default fs-14 default-text-color">
              New Password
            </label>
            <input
              type="password"
              className={`form-control ${password ? (validatePwdInput ? 'is-valid' : 'is-invalid') : ''}`}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className="d-flex flex-column justify-content-start align-items-start gap-1 w-100">
            <label className="text-start font-default fs-14 default-text-color">
              Retype New Password
            </label>
            <input
              type="password"
              className={`form-control ${passwordConfirmation ? (validatePwdConfirmInput ? 'is-valid' : 'is-invalid') : ''}`}
              value={passwordConfirmation}
              onChange={(e) => setPasswordConfirmation(e.target.value)}
            />
          </div>
        </div>
        <span className="fs-12 font-merge color-grey text-center">
          Password must be at least {minimalLength} characters long.
        </span>
        <button
          className="btn btn-pink"
          onClick={handleUpdatePassword}
          disabled={!allFieldsSet}
        >
          Change Password
        </button>
      </div>
    </SettingsLayout>
  );
}
