// frontend/src/pages/Settings/Profile.vue
<script setup>
import { ref, reactive, onMounted, computed, defineAsyncComponent } from 'vue';
import { useForm } from '@/helpers/useForm'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { $t } from '@/i18n.js';
import { BForm, BInput, BFormSelect, BFormTextarea } from 'bootstrap-vue-next';
import { removeEmptyObjectsKeys } from '@/Services/FormService.js';
const SettingsLayout = defineAsyncComponent(() => import('@/Layouts/SettingsLayout.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
import route from "@/helpers/route"

const genders = ref(null);
const countries = ref(null);
const loading = ref(true);

  onMounted(async () => {
    try {
      const response = await apiClient.get('/settings/profile');
      const apiData = response.data;
      genders.value = apiData.genders ?? null;
    countries.value = apiData.countries ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const authStore = useAuthStore();
const user = authStore.user;
const today = new Date(Date.now()).toJSON().substring(0, 10);

const form = useForm({
    name: user.name,
    bio: user.bio,
    birth: user.birth,
    gender: user.gender,
    country_id: user.country,
});

const onSubmit = (e) => {
    e.preventDefault();

    form.transform(removeEmptyObjectsKeys).patch(route('settings.profile.update'), {
        preserveScroll: true,
        preserveState: true,
    });
};

const reset = () => {
    form.reset();
};

const countryOptions = computed(() =>
    countries.map((element) => {
        return {
            value: element.id,
            text: element.name,
        };
    }),
);
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <SettingsLayout :title="$t('menus.user_settings.profile')">
        <BForm class="row gy-4" @submit="onSubmit" @reset="reset">
            <div class="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
                <label class="font-default fs-14 default-text-color">
                    {{ $t('pages.settings.profile_display_name_title') }}:
                </label>
                <BInput type="text" max="175" v-model="form.name" />
                <span class="fs-12 font-merge color-grey">
                    {{ $t('pages.settings.profile_display_name_description') }}
                </span>
            </div>
            <div class="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
                <label class="font-default fs-14 default-text-color">
                    {{ $t('pages.settings.profile_country_title') }}:
                </label>
                <BFormSelect v-model="form.country_id" :options="countryOptions"></BFormSelect>
                <span class="fs-12 font-merge color-grey">
                    {{ $t('pages.settings.profile_country_description') }}
                </span>
            </div>
            <div class="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
                <label class="font-default fs-14 default-text-color">
                    {{ $t('pages.settings.profile_gender_title') }}:
                </label>
                <BFormSelect v-model="form.gender" :options="genders"></BFormSelect>
                <span class="fs-12 font-merge color-grey">
                    {{ $t('pages.settings.profile_gender_description') }}
                </span>
            </div>
            <div class="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
                <label class="font-default fs-14 default-text-color">
                    {{ $t('pages.settings.profile_birth_title') }}:
                </label>
                <BInput type="date" v-model="form.birth" :max="today" />
                <span class="fs-12 font-merge color-grey">
                    {{ $t('pages.settings.profile_birth_description') }}
                </span>
            </div>
            <div class="col-12 d-flex flex-column justify-content-start align-items-start gap-1">
                <label class="font-default fs-14 default-text-color">
                    {{ $t('pages.settings.profile_bio_title') }}:
                </label>
                <BFormTextarea max="180" v-model="form.bio" />
                <span class="fs-12 font-merge color-grey">
                    {{ $t('pages.settings.profile_bio_description') }}
                </span>
            </div>
            <div class="col-12 d-flex flex-row justify-content-center align-items-center gap-4 mt-5">
                <DefaultButton type="submit" class-list="btn-pink">
                    {{ $t('buttons.save_changes') }}
                </DefaultButton>
            </div>
        </BForm>
    </SettingsLayout>
</template>
  </template>

// frontend/src/pages/Settings/Profile.tsx
import React, { useState, useEffect } from 'react';
import { useAuthStore } from '@/stores/auth';
import apiClient from '@/api/client';
import { SETTINGS } from '@/api/endpoints';
import SettingsLayout from '@/Layouts/SettingsLayout';

export default function SettingsProfile() {
  const [genders, setGenders] = useState<any[]>([]);
  const [countries, setCountries] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const authUser = useAuthStore((s) => s.user);

  const [name, setName] = useState(authUser?.name || '');
  const [bio, setBio] = useState(authUser?.bio || '');
  const [birth, setBirth] = useState(authUser?.birth || '');
  const [gender, setGender] = useState(authUser?.gender || '');
  const [countryId, setCountryId] = useState(authUser?.country || '');

  const today = new Date().toISOString().substring(0, 10);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get(SETTINGS.PROFILE);
        const apiData = response.data;
        setGenders(apiData.genders ?? []);
        setCountries(apiData.countries ?? []);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await apiClient.patch(SETTINGS.PROFILE, {
        name,
        bio,
        birth,
        gender,
        country_id: countryId,
      });
    } catch (error) {
      console.error('Failed to update profile:', error);
    }
  };

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <SettingsLayout title="Profile">
      <form className="row gy-4" onSubmit={handleSubmit}>
        <div className="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
          <label className="font-default fs-14 default-text-color">Display Name:</label>
          <input
            type="text"
            className="form-control"
            maxLength={175}
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <span className="fs-12 font-merge color-grey">
            Your display name visible to other users.
          </span>
        </div>
        <div className="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
          <label className="font-default fs-14 default-text-color">Country:</label>
          <select
            className="form-select"
            value={countryId}
            onChange={(e) => setCountryId(e.target.value)}
          >
            <option value="">Select country</option>
            {countries.map((country: any) => (
              <option key={country.id} value={country.id}>
                {country.name}
              </option>
            ))}
          </select>
          <span className="fs-12 font-merge color-grey">
            Your country location.
          </span>
        </div>
        <div className="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
          <label className="font-default fs-14 default-text-color">Gender:</label>
          <select
            className="form-select"
            value={gender}
            onChange={(e) => setGender(e.target.value)}
          >
            <option value="">Select gender</option>
            {genders.map((g: any, index: number) => (
              <option key={index} value={g.value ?? g}>
                {g.text ?? g}
              </option>
            ))}
          </select>
          <span className="fs-12 font-merge color-grey">
            Your gender identity.
          </span>
        </div>
        <div className="col-12 col-lg-6 d-flex flex-column justify-content-start align-items-start gap-1">
          <label className="font-default fs-14 default-text-color">Birth Date:</label>
          <input
            type="date"
            className="form-control"
            value={birth}
            max={today}
            onChange={(e) => setBirth(e.target.value)}
          />
          <span className="fs-12 font-merge color-grey">
            Your birth date.
          </span>
        </div>
        <div className="col-12 d-flex flex-column justify-content-start align-items-start gap-1">
          <label className="font-default fs-14 default-text-color">Bio:</label>
          <textarea
            className="form-control"
            maxLength={180}
            value={bio}
            onChange={(e) => setBio(e.target.value)}
          />
          <span className="fs-12 font-merge color-grey">
            A short bio about yourself.
          </span>
        </div>
        <div className="col-12 d-flex flex-row justify-content-center align-items-center gap-4 mt-5">
          <button type="submit" className="btn btn-pink">
            Save Changes
          </button>
        </div>
      </form>
    </SettingsLayout>
  );
}
