// frontend/src/pages/Settings/Subscription.vue
<script setup>
import { ref, reactive, onMounted, computed, defineAsyncComponent } from 'vue';
import { useRoute, useRouter } from 'vue-router'
import apiClient from '@/api/client'
import { $t } from '@/i18n.js';
import { subscriptionAssetImage } from '@/Services/AssetService.js';
const SettingsLayout = defineAsyncComponent(() => import('@/Layouts/SettingsLayout.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
import route from "@/helpers/route"

const subscription = ref(null);
const plans = ref(null);
const loading = ref(true);

  onMounted(async () => {
    try {
      const response = await apiClient.get('/settings/subscription');
      const apiData = response.data;
      subscription.value = apiData.subscription ?? null;
    plans.value = apiData.plans ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const submit = () => {
    form.patch(route('subscription.update'), {
        preserveScroll: true,
    });
};

const suspendSubscription = () => {
    apiClient.post(route('settings.subscription.suspend'), {
        preserveScroll: true,
    });
};

const activateSubscription = () => {
    apiClient.post(route('settings.subscription.activate'), {
        preserveScroll: true,
    });
};

const cancelSubscription = () => {
    apiClient.post(route('settings.subscription.cancel'), {
        preserveScroll: true,
    });
};

const subscriptionActionName = computed(() =>
    subscription.value?.status === 'active' ? $t('buttons.suspend_subscription') : $t('buttons.activate_subscription'),
);
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <SettingsLayout :title="$t('menus.user_settings.subscription')">
        <div class="d-flex flex-column justify-content-center align-items-center gap-4">
            <img :src="subscriptionAssetImage" alt="$t('menus.user_settings.subscription')" />
            <template v-if="subscription">
                <DefaultButton
                    class-list="btn-pink btn-wide"
                    @click="subscription.status === 'active' ? suspendSubscription() : activateSubscription()"
                >
                    {{ subscriptionActionName }}
                </DefaultButton>
                <DefaultButton class-list="btn-pink btn-wide" @click="cancelSubscription()">
                    {{ $t('buttons.cancel_subscription') }}
                </DefaultButton>
            </template>
            <template v-else>
                <div class="font-default fs-5 fw-bolder">
                    {{ $t('pages.settings.subscription_title') }}
                </div>
                <div class="text-start font-default fs-14">
                    <p>- {{ $t('pages.settings.subscription_feature_1') }}</p>
                    <p>- {{ $t('pages.settings.subscription_feature_2') }}</p>
                    <p>- {{ $t('pages.settings.subscription_feature_3') }}</p>
                    <p>- {{ $t('pages.settings.subscription_feature_4') }}</p>
                    <p>- {{ $t('pages.settings.subscription_feature_5') }}</p>
                </div>
                <DefaultButton :href="route('settings.subscription.checkout')" class-list="btn-pink">
                    {{ $t('buttons.subscribe_site') }}
                </DefaultButton>
            </template>
        </div>
    </SettingsLayout>
</template>
  </template>

// frontend/src/pages/Settings/Subscription.tsx
import React, { useState, useEffect, useMemo } from 'react';
import apiClient from '@/api/client';
import { SETTINGS, SUBSCRIPTIONS } from '@/api/endpoints';
import SettingsLayout from '@/Layouts/SettingsLayout';

export default function SettingsSubscription() {
  const [subscription, setSubscription] = useState<any>(null);
  const [plans, setPlans] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get(SETTINGS.SUBSCRIPTION);
        const apiData = response.data;
        setSubscription(apiData.subscription ?? null);
        setPlans(apiData.plans ?? []);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleSuspend = async () => {
    try {
      await apiClient.post(SUBSCRIPTIONS.SUSPEND);
      setSubscription((prev: any) => prev ? { ...prev, status: 'suspended' } : prev);
    } catch (error) {
      console.error('Failed to suspend subscription:', error);
    }
  };

  const handleActivate = async () => {
    try {
      await apiClient.post(SUBSCRIPTIONS.ACTIVATE);
      setSubscription((prev: any) => prev ? { ...prev, status: 'active' } : prev);
    } catch (error) {
      console.error('Failed to activate subscription:', error);
    }
  };

  const handleCancel = async () => {
    try {
      await apiClient.post(SUBSCRIPTIONS.CANCEL);
      setSubscription(null);
    } catch (error) {
      console.error('Failed to cancel subscription:', error);
    }
  };

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  const subscriptionActionName = subscription?.status === 'active'
    ? 'Suspend Subscription'
    : 'Activate Subscription';

  return (
    <SettingsLayout title="Subscription">
      <div className="d-flex flex-column justify-content-center align-items-center gap-4">
        {subscription ? (
          <>
            <button
              className="btn btn-pink btn-wide"
              onClick={subscription.status === 'active' ? handleSuspend : handleActivate}
            >
              {subscriptionActionName}
            </button>
            <button className="btn btn-pink btn-wide" onClick={handleCancel}>
              Cancel Subscription
            </button>
          </>
        ) : (
          <>
            <div className="font-default fs-5 fw-bolder">
              Subscribe to unlock premium features
            </div>
            <div className="text-start font-default fs-14">
              <p>- Unlimited uploads</p>
              <p>- Priority support</p>
              <p>- Advanced analytics</p>
              <p>- Ad-free experience</p>
              <p>- Exclusive content</p>
            </div>
            <a href={SUBSCRIPTIONS.CHECKOUT} className="btn btn-pink">
              Subscribe Now
            </a>
          </>
        )}
      </div>
    </SettingsLayout>
  );
}
