// frontend/src/pages/Genre/Index.vue
<script setup>
import apiClient from "@/api/client";
import { $t } from '@/i18n.js';
import { defineAsyncComponent, ref, onMounted } from 'vue';
const ImageCard = defineAsyncComponent(() => import('@/Components/Cards/ImageCard.vue'));
import route from "@/helpers/route"

const genres = ref(null);
const loading = ref(true);

  onMounted(async () => {
    try {
      const response = await apiClient.get('/genres');
      const apiData = response.data;
      genres.value = apiData.genres ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    <div class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
        <div class="container">
            <div class="row">
                <div class="col text-start">
                    <div class="d-block">
                        <div class="block-title color-light text-truncate">
                            {{ $t('pages.genres.title') }}
                        </div>
                        <div class="block-description color-light">
                            {{ $t('pages.genres.description') }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <div class="d-flex flex-row justify-content-center flex-wrap align-items-center gap-2 gap-lg-4">
                        <ImageCard
                            v-for="genre in genres"
                            :model="genre"
                            :route="route('genres.show', genre.slug)"
                            :key="genre.uuid"
                        />
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
  </template>

// frontend/src/pages/Genre/Index.tsx
import React, { useState, useEffect } from 'react';
import apiClient from '@/api/client';
import { $t } from '@/i18n';
import ImageCard from '@/Components/Cards/ImageCard';
import route from '@/helpers/route';

export default function GenreIndexPage() {
  const [genres, setGenres] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get('/genres');
        const apiData = response.data;
        setGenres(apiData.genres ?? null);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
      <div className="container">
        <div className="row">
          <div className="col text-start">
            <div className="d-block">
              <div className="block-title color-light text-truncate">
                {$t('pages.genres.title')}
              </div>
              <div className="block-description color-light">
                {$t('pages.genres.description')}
              </div>
            </div>
          </div>
        </div>
        <div className="row mt-3">
          <div className="col">
            <div className="d-flex flex-row justify-content-center flex-wrap align-items-center gap-2 gap-lg-4">
              {genres?.map((genre: any) => (
                <ImageCard
                  key={genre.uuid}
                  model={genre}
                  route={route('genres.show', genre.slug)}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
