// frontend/src/pages/Adventures/Show.vue
<script setup>
import { $t } from '@/i18n.js';
import { computed, defineAsyncComponent, ref, reactive, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { useAudioPlayerStore } from '@/stores/track.js';
import { storeToRefs } from 'pinia';
import { useModal, useVfm } from 'vue-final-modal';
import { BDropdown, BDropdownItem, BDropdownItemButton } from 'bootstrap-vue-next';
import { isNotEmpty } from '@/Services/MiscService.js';
import { isLogged } from '@/Services/AuthService.js';
import ObjectTypes from '@/Enums/ObjectTypes.js';
const UserLayout = defineAsyncComponent(() => import('@/Layouts/UserLayout.vue'));
const CircledText = defineAsyncComponent(() => import('@/Components/CircledText.vue'));
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const CommentsSection = defineAsyncComponent(() => import('@/Components/Sections/CommentsSection.vue'));
const ConfirmDeletionModal = defineAsyncComponent(() => import('@/Components/Modals/ConfirmDeletionModal.vue'));
const ShareModal = defineAsyncComponent(() => import('@/Components/Modals/ShareModal.vue'));
const ReportModal = defineAsyncComponent(() => import('@/Components/Modals/ReportModal.vue'));
const AdventureMapModal = defineAsyncComponent(() => import('@/Components/Modals/AdventureMapModal.vue'));
import route from "@/helpers/route"

const audioPlayer = useAudioPlayerStore();
const { isPlaying, currentTrack } = storeToRefs(audioPlayer);

const adventure = ref(null);
const user = ref(null);
const comments = ref(null);
const loading = ref(true);
const currentRoute = useRoute();

  onMounted(async () => {
    try {
      const response = await apiClient.get(`/adventures/${currentRoute.params.uuid}`);
      const apiData = response.data;
      adventure.value = apiData.adventure ?? null;
    user.value = apiData.user ?? null;
    comments.value = apiData.comments ?? null;
    } catch (error) {
      console.error('Failed to load page data:', error);
    } finally {
      loading.value = false;
    }
  });

const loggedUser = useAuthStore().user;
const vfm = useVfm();

const hasDescription = computed(() => adventure.value?.description?.length > 0);
const isOwned = computed(() => loggedUser && loggedUser.uuid === user.value?.uuid);
const isCurrentTrack = computed(() => currentTrack.value?.uuid === adventure.value?.uuid);
const totalTracks = computed(() => {
    if (!adventure.value?.children) return 0;
    let total = adventure.value.children.length;

    for (const root of adventure.value.children) {
        if (isNotEmpty(root.children)) {
            total += root.children.length;
        }
    }

    return total + 1;
});

const addToFavorites = () => {
    apiClient.post(
        route('users.favorites.store', {
            user: loggedUser.uuid,
        }),
        {
            uuid: adventure.value?.uuid,
            type: ObjectTypes.Adventure,
        },
        {
            preserveState: true,
            preserveScroll: true,
        },
    );
};

const openDeleteModal = () =>
    useModal({
        component: ConfirmDeletionModal,
        attrs: {
            title: adventure.value?.title,
            type: ObjectTypes.Adventure,
            onClose() {
                vfm.close('delete-modal');
            },
            onConfirm() {
                apiClient.delete(route('adventures.destroy', adventure.value));
                vfm.close('delete-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const openShareModal = () =>
    useModal({
        component: ShareModal,
        attrs: {
            title: adventure.value?.title,
            item: adventure.value,
            onClose() {
                vfm.close('share-modal');
            },
            onConfirm() {
                vfm.close('share-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const openReportModal = () =>
    useModal({
        component: ReportModal,
        attrs: {
            item: adventure.value,
            type: ObjectTypes.Adventure,
            onClose() {
                vfm.close('report-modal');
            },
            onConfirm() {
                vfm.close('report-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const openMapModal = () =>
    useModal({
        component: AdventureMapModal,
        attrs: {
            adventure: adventure.value,
            onClose() {
                vfm.close('adventure-map-modal');
            },
            onConfirm() {
                vfm.close('adventure-map-modal');
            },
        },
        clickToClose: true,
        escToClose: true,
    }).open();

const updateComments = async () => {
  try {
    const response = await apiClient.get(currentRoute.path.replace(/^\//, ''));
    const apiData = response.data;
    if (apiData.comments) comments.value = apiData.comments;
  } catch (error) {
    console.error('Failed to refresh comments:', error);
  }
};

const handlePlayClick = () => {
    try {
        if (isCurrentTrack.value) {
            audioPlayer.togglePlayPause();
        } else {
            audioPlayer.setTracks(adventure.value);
        }
    } catch (error) {
        console.error('Failed to play track:', error);
    }
};
</script>

<template>
      <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
          <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
      </div>
      <template v-else>
    
    <UserLayout :user="user">
        <div class="row gy-3">
            <div
                class="col-12 col-lg-4 d-flex flex-column gap-3 justify-content-center justify-content-xl-start align-items-start"
            >
                <img :src="adventure.artwork" :alt="adventure.title" class="img-fluid rounded-4 border-pink" />
            </div>
            <div class="col">
                <div class="d-flex flex-column gap-3">
                    <div
                        v-if="isLogged"
                        class="d-flex flex-row gap-4 justify-content-xl-start justify-content-center align-items-start flex-wrap"
                    >
                        <CircledText :title="totalTracks" :description="$t('pages.adventure.total_tracks')" />
                        <CircledText :title="adventure.likes" :description="$t('misc.likes')" />
                        <BDropdown no-wrapper no-caret toggle-class="btn-default p-2 btn-icon ms-auto">
                            <template #button-content>
                                <Icon :icon="['fas', 'ellipsis-vertical']" />
                            </template>
                            <BDropdownItemButton @click="addToFavorites">
                                {{ $t('menus.track.add_to_favorites') }}
                            </BDropdownItemButton>
                            <BDropdownItemButton @click="openMapModal">
                                {{ $t('buttons.show_map') }}
                            </BDropdownItemButton>
                            <BDropdownItemButton @click="openShareModal">
                                {{ $t('menus.track.share') }}
                            </BDropdownItemButton>
                            <BDropdownItemButton @click="openReportModal">
                                {{ $t('menus.track.report') }}
                            </BDropdownItemButton>
                            <BDropdownItem v-if="isOwned" :href="route('adventures.edit', adventure)">
                                {{ $t('buttons.edit') }}
                            </BDropdownItem>
                            <BDropdownItemButton v-if="isOwned" @click="openDeleteModal">
                                {{ $t('buttons.delete') }}
                            </BDropdownItemButton>
                        </BDropdown>
                    </div>
                    <div class="d-flex flex-row align-items-center py-3 border-top border-bottom gap-3">
                        <div class="d-block">
                            <button class="btn-play lg" @click="handlePlayClick" :disabled="!isLogged">
                                <Icon
                                    :class="{ 'ms-1': !isPlaying || !isCurrentTrack }"
                                    :icon="['fas', isPlaying && isCurrentTrack ? 'pause' : 'play']"
                                    size="2xl"
                                />
                            </button>
                        </div>
                        <div class="d-flex flex-column align-items-start justify-content-start gap-2">
                            <span class="font-default fs-4">{{ adventure.title }}</span>
                            <span class="font-merge">{{ adventure.user.name }}</span>
                            <div class="d-flex flex-row justify-content-start align-items-center gap-2">
                                <Icon :icon="['fas', 'calendar-check']" class-list="color-pink" />
                                <span class="font-merge">
                                    {{ adventure.created_at }}
                                </span>
                            </div>
                        </div>
                    </div>
                    <div v-if="isNotEmpty(adventure.tags)" class="d-flex flex-row gap-2 border-bottom pb-3 flex-wrap">
                        <a
                            v-for="tag in adventure.tags"
                            :href="route('discover.index', { tags: tag.tag })"
                            class="btn-default btn-outline btn-narrow"
                        >
                            {{ tag.tag }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div v-if="hasDescription" class="d-flex flex-row text-start my-3">
            <span class="font-default">{{ $t('misc.summary', { text: adventure.description }) }}</span>
        </div>
        <template v-if="isLogged && adventure.allow_comments" #comments>
            <CommentsSection
                :comments="comments"
                :type="adventure.type"
                :uuid="adventure.uuid"
                @commented="updateComments"
            />
        </template>
    </UserLayout>
</template>
  </template>

// frontend/src/pages/Adventures/Show.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';
import UserLayout from '@/Layouts/UserLayout';

export default function AdventuresShow() {
    const { uuid } = useParams<{ uuid: string }>();
    const [adventure, setAdventure] = useState<any>(null);
    const [user, setUser] = useState<any>(null);
    const [comments, setComments] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    const loggedUser = useAuthStore((s) => s.user);
    const isLogged = useAuthStore((s) => s.isLogged);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await apiClient.get(`/adventures/${uuid}`);
                const apiData = response.data;
                setAdventure(apiData.adventure ?? null);
                setUser(apiData.user ?? null);
                setComments(apiData.comments ?? null);
            } catch (error) {
                console.error('Failed to load page data:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [uuid]);

    const isOwned = useMemo(() => loggedUser && loggedUser.uuid === user?.uuid, [loggedUser, user]);

    const totalTracks = useMemo(() => {
        if (!adventure?.children) return 0;
        let total = adventure.children.length;
        for (const root of adventure.children) {
            if (root.children && root.children.length > 0) {
                total += root.children.length;
            }
        }
        return total + 1;
    }, [adventure]);

    const updateComments = async () => {
        try {
            const response = await apiClient.get(`/adventures/${uuid}`);
            const apiData = response.data;
            if (apiData.comments) setComments(apiData.comments);
        } catch (error) {
            console.error('Failed to refresh comments:', error);
        }
    };

    if (loading) {
        return (
            <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
                <div className="spinner-border text-light" role="status">
                    <span className="visually-hidden">Loading...</span>
                </div>
            </div>
        );
    }

    if (!adventure) return null;

    return (
        <UserLayout user={user}>
            <div className="row gy-3">
                <div className="col-12 col-lg-4 d-flex flex-column gap-3 justify-content-center justify-content-xl-start align-items-start">
                    <img src={adventure.artwork} alt={adventure.title} className="img-fluid rounded-4 border-pink" />
                </div>
                <div className="col">
                    <div className="d-flex flex-column gap-3">
                        {isLogged && (
                            <div className="d-flex flex-row gap-4 justify-content-xl-start justify-content-center align-items-start flex-wrap">
                                <div className="text-center">
                                    <div className="font-default">{totalTracks}</div>
                                    <div className="font-merge">Total Tracks</div>
                                </div>
                                <div className="text-center">
                                    <div className="font-default">{adventure.likes}</div>
                                    <div className="font-merge">Likes</div>
                                </div>
                            </div>
                        )}
                        <div className="d-flex flex-row align-items-center py-3 border-top border-bottom gap-3">
                            <div className="d-block">
                                <button className="btn-play lg" disabled={!isLogged}>
                                    <i className="fas fa-play ms-1" />
                                </button>
                            </div>
                            <div className="d-flex flex-column align-items-start justify-content-start gap-2">
                                <span className="font-default fs-4">{adventure.title}</span>
                                <span className="font-merge">{adventure.user?.name}</span>
                                <div className="d-flex flex-row justify-content-start align-items-center gap-2">
                                    <i className="fas fa-calendar-check color-pink" />
                                    <span className="font-merge">{adventure.created_at}</span>
                                </div>
                            </div>
                        </div>
                        {adventure.tags && adventure.tags.length > 0 && (
                            <div className="d-flex flex-row gap-2 border-bottom pb-3 flex-wrap">
                                {adventure.tags.map((tag: any, idx: number) => (
                                    <Link key={idx} to={`/discover?tags=${tag.tag}`} className="btn-default btn-outline btn-narrow">
                                        {tag.tag}
                                    </Link>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </div>
            {adventure.description && (
                <div className="d-flex flex-row text-start my-3">
                    <span className="font-default">{adventure.description}</span>
                </div>
            )}
        </UserLayout>
    );
}
