// frontend/src/pages/Channel/Show.vue
<script setup>
import { $t } from '@/i18n.js';
import { computed, defineAsyncComponent, ref, onMounted } from 'vue';
import { useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import apiClient from '@/api/client'
import { isLogged } from '@/Services/AuthService.js';
import ObjectTypes from '@/Enums/ObjectTypes.js';
import { addToFavorites, removeFromFavorites } from '@/Services/FavoriteService.js';
const Song = defineAsyncComponent(() => import('@/Components/Song.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));

const currentRoute = useRoute();
const channel = ref(null);
const objects = ref([]);
const pagination = ref(null);
const loading = ref(true);

const authStore = useAuthStore();
const user = computed(() => authStore?.user);
const lastPage = computed(() => !pagination.value || pagination.value.current_page >= pagination.value.last_page);

const fetchData = async (page = 1) => {
  try {
    const response = await apiClient.get(`/channels/${currentRoute.params.slug}`, { params: { page } });
    const apiData = response.data;
    channel.value = apiData.channel ?? null;
    if (page === 1) {
      objects.value = apiData.objects ?? [];
    } else {
      objects.value = [...objects.value, ...(apiData.objects ?? [])];
    }
    pagination.value = apiData.pagination ?? null;
  } catch (error) {
    console.error('Failed to load page data:', error);
  } finally {
    loading.value = false;
  }
};

onMounted(() => fetchData());

const loadMore = () => {
  if (pagination.value) {
    fetchData(pagination.value.current_page + 1);
  }
};
</script>

<template>
    <div v-if="loading" class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div class="spinner-border text-light" role="status"><span class="visually-hidden">Loading...</span></div>
    </div>
    <div v-else class="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
        <div class="container">
            <div class="row">
                <div class="col text-start">
                    <div class="d-block">
                        <div class="block-title color-light text-truncate">
                            {{ channel?.title }}
                        </div>
                        <div class="block-description color-light">
                            {{ channel?.description }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col flex-column">
                    <template v-if="channel?.type === ObjectTypes.Song">
                        <Song
                            v-for="song in objects"
                            :song="song"
                            :key="song.uuid"
                            :can-view="isLogged"
                            :is-owned="user?.uuid === song.user?.uuid"
                            @add-to-favorites="addToFavorites($event, authStore.user?.uuid)"
                            @remove-from-favorites="removeFromFavorites($event, authStore.user?.uuid)"
                        />
                    </template>
                    <DefaultButton class-list="btn-outline mt-2 mx-auto" @click="loadMore" :disabled="lastPage">
                        {{ $t('buttons.load_more') }}
                    </DefaultButton>
                </div>
            </div>
        </div>
    </div>
</template>

// frontend/src/pages/Blog/Show.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import apiClient from '@/api/client';
import { $t } from '@/i18n';
import CommentsSection from '@/Components/Sections/CommentsSection';
import route from '@/helpers/route';

export default function BlogShowPage() {
  const { slug } = useParams<{ slug: string }>();
  const [post, setPost] = useState<any>(null);
  const [comments, setComments] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await apiClient.get(`/blog/${slug}`);
        const apiData = response.data;
        setPost(apiData.post ?? null);
        setComments(apiData.comments ?? null);
      } catch (error) {
        console.error('Failed to load page data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [slug]);

  const updateComments = async () => {
    try {
      const response = await apiClient.get(`/blog/${slug}`);
      const apiData = response.data;
      if (apiData.comments) setComments(apiData.comments);
    } catch (error) {
      console.error('Failed to refresh comments:', error);
    }
  };

  const content = useMemo(
    () => (post?.full_content ? post.full_content : post?.short_content),
    [post]
  );

  if (loading) {
    return (
      <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100 d-flex justify-content-center align-items-center">
        <div className="spinner-border text-light" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  if (!post) return null;

  return (
    <div className="bg-gradient-default py-3 p-md-5 p-lg-6 min-vh-100">
      <div className="container d-flex flex-column gap-4">
        <div className="row">
          <div className="col text-start">
            <div className="d-block">
              <div className="block-title color-light text-truncate">
                {post.title}
              </div>
              <a href={route('posts.index')} className="block-description color-light">
                {$t('misc.back')}
              </a>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <div className="d-flex flex-column justify-content-center align-items-center gap-4 bg-default rounded-5 p-5 h-100">
              {post.artwork && (
                <img className="img-fluid" alt={post.title} src={post.artwork} />
              )}
              {content && (
                <div className="fs-5" dangerouslySetInnerHTML={{ __html: content }} />
              )}
            </div>
          </div>
        </div>
        {post.allow_comments ? (
          <div className="row">
            <CommentsSection
              comments={comments}
              type={post.type}
              uuid={post.uuid}
              onCommented={updateComments}
            />
          </div>
        ) : (
          <div className="row text-center color-light font-default fs-5">
            <span>{$t('misc.comments_disabled')}</span>
          </div>
        )}
      </div>
    </div>
  );
}
