// frontend/src/Components/Player/VolumeController.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useAudioPlayerStore } from '@/stores/track';
import IconButton from '@/Components/Buttons/IconButton';

export default function VolumeController() {
    const audioPlayer = useAudioPlayerStore();
    const storeVolume = audioPlayer.volume;

    const [isHover, setIsHover] = useState(false);
    const [isMuted, setIsMuted] = useState(false);
    const [volumeLevel, setVolumeLevel] = useState(Math.round(storeVolume * 100));
    const [volumePercentage, setVolumePercentage] = useState(Math.round(storeVolume * 100));

    const toggleVolume = () => {
        const newMuted = !isMuted;
        setIsMuted(newMuted);
        const newVolume = newMuted ? 0 : volumeLevel / 100;
        audioPlayer.setVolume(newVolume);
        setVolumePercentage(newMuted ? 0 : volumeLevel);
    };

    const handleVolumeInput = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = parseInt(e.target.value);
        setVolumePercentage(value);
        audioPlayer.setVolume(value / 100);
        if (value === 0) {
            setIsMuted(true);
        } else {
            setIsMuted(false);
            setVolumeLevel(value);
        }
    };

    useEffect(() => {
        const newPercentage = Math.round(storeVolume * 100);
        setVolumePercentage(newPercentage);
        if (storeVolume === 0) {
            setIsMuted(true);
        } else {
            setIsMuted(false);
            setVolumeLevel(newPercentage);
        }
    }, [storeVolume]);

    const volumeIcon = isMuted || volumePercentage === 0
        ? 'volume-xmark'
        : volumePercentage < 50
            ? 'volume-low'
            : 'volume-high';

    return (
        <div className="d-none d-lg-flex flex-row justify-content-end align-items-center gap-3 w-75">
            <IconButton icon={volumeIcon} onClick={toggleVolume} classList="w-25" />
            <div
                className="volume-control w-75"
                onMouseOver={() => setIsHover(true)}
                onMouseLeave={() => setIsHover(false)}
                style={{ display: 'grid', gridTemplateAreas: "'stack'", alignItems: 'center', position: 'relative', width: '200px', height: '20px' }}
            >
                <div
                    className="volume-bar rounded"
                    style={{ width: `${volumePercentage}%`, gridArea: 'stack', backgroundColor: 'var(--primary-color, #e836c5)', height: '8px', zIndex: 2, pointerEvents: 'none' }}
                />
                <input
                    value={volumePercentage}
                    type="range"
                    className="volume-slider w-100"
                    min="0"
                    max="100"
                    onChange={handleVolumeInput}
                    style={{ gridArea: 'stack', WebkitAppearance: 'none', background: 'transparent', width: '100%', height: '100%', zIndex: 1, cursor: 'pointer' }}
                />
            </div>
        </div>
    );
}

// Afterdarkv2-main/resources/js/Components/Player/VolumeController.vue
<script setup>
import { useAudioPlayerStore } from '@/stores/track.js';
import { storeToRefs } from 'pinia';
import { onMounted, ref, watch, onBeforeUnmount, defineAsyncComponent } from 'vue';
const IconButton = defineAsyncComponent(() => import('@/Components/Buttons/IconButton.vue'));

const audioPlayer = useAudioPlayerStore();
const { volume: storeVolume } = storeToRefs(audioPlayer);

const isHover = ref(false);
const isMuted = ref(false);
const volumeLevel = ref(Math.round(storeVolume.value * 100));
const volumeInput = ref(null);

// Convert store volume (0-1) to percentage (0-100) for display
const volumePercentage = ref(Math.round(storeVolume.value * 100));

const toggleVolume = () => {
    isMuted.value = !isMuted.value;
};

const handleVolumeInput = (e) => {
    const value = parseInt(e.currentTarget.value);
    volumePercentage.value = value;
    audioPlayer.setVolume(value / 100);

    if (value === 0) {
        isMuted.value = true;
    } else {
        isMuted.value = false;
        volumeLevel.value = value;
    }
};

watch(
    () => isMuted.value,
    (newValue) => {
        const newVolume = newValue ? 0 : volumeLevel.value / 100;
        audioPlayer.setVolume(newVolume);
        volumePercentage.value = newValue ? 0 : volumeLevel.value;
    },
);

// Watch store volume changes and update local state
watch(
    () => storeVolume.value,
    (newValue) => {
        volumePercentage.value = Math.round(newValue * 100);
        if (newValue === 0) {
            isMuted.value = true;
        } else {
            isMuted.value = false;
            volumeLevel.value = volumePercentage.value;
        }
    },
);

onMounted(() => {
    if (volumeInput.value) {
        volumeInput.value.addEventListener('input', handleVolumeInput);
    }
});

onBeforeUnmount(() => {
    if (volumeInput.value) {
        volumeInput.value.removeEventListener('input', handleVolumeInput);
    }
});
</script>

<template>
    <div class="d-flex flex-row justify-content-end align-items-center gap-3 w-75">
        <IconButton
            :icon="
                isMuted || volumePercentage === 0
                    ? 'volume-xmark'
                    : volumePercentage < 50
                      ? 'volume-low'
                      : 'volume-high'
            "
            @click="toggleVolume"
            class-list="w-25"
        />
        <div class="volume-control w-75" @mouseover="isHover = true" @mouseleave="isHover = false">
            <div class="volume-bar rounded" :style="`width: ${volumePercentage}%;`" />
            <input
                ref="volumeInput"
                :value="volumePercentage"
                type="range"
                class="volume-slider w-100"
                min="0"
                max="100"
            />
        </div>
    </div>
</template>

<style scoped>
.volume-control {
    display: grid;
    grid-template-areas: 'stack';
    align-items: center;
    position: relative;
    width: 200px; /* Adjust as needed */
    height: 20px; /* Adjust as needed */
}

.volume-bar,
.volume-slider {
    grid-area: stack;
}

.volume-bar {
    background-color: var(--primary-color, #e836c5);
    height: 8px;
    z-index: 2; /* Ensure the bar is behind the thumb */
    pointer-events: none; /* Make the bar non-interactive */
}

.volume-slider {
    -webkit-appearance: none;
    background: transparent;
    width: 100%;
    height: 100%;
    z-index: 1; /* Ensure the slider is interactive */
    cursor: pointer;
}

/* Customizing the thumb for consistent styling */
.volume-slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 20px;
    height: 20px;
    background: var(--primary-color, #e836c5);
    border: 1px solid #ccc;
    border-radius: 50%;
    margin-top: -6px; /* Adjust to center the thumb vertically */
}

/* Customizing the track (the gray line) */
.volume-slider::-webkit-slider-runnable-track {
    width: 100%;
    height: 8px;
    background: #ddd;
    border-radius: 4px;
}
</style>
