// frontend/src/Components/Modals/AdultOnlyModal.vue
<script setup>
import { VueFinalModal } from 'vue-final-modal';
import { $t } from '@/i18n.js';
import { useRouter } from 'vue-router'
import apiClient from '@/api/client';
import { defineAsyncComponent, ref } from 'vue';
import { BOverlay } from 'bootstrap-vue-next';
const DefaultLink = defineAsyncComponent(() => import('@/Components/Links/DefaultLink.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
import route from "@/helpers/route"

const processing = ref(false);
const emit = defineEmits(['accepted']);

const accept = () => {
    processing.value = true;

    apiClient.post(
        route('terms.accept'),
        {
            accept: true,
        },
        {
            preserveState: true,
            preserveScroll: true,
            onSuccess: () => {
                processing.value = false;
                emit('accepted');
            },
            onError: () => {
                processing.value = false;
            },
        },
    );
};
</script>

<template>
    <VueFinalModal
        class="d-flex justify-content-center align-items-center"
        content-class="lightbox-warning-18 position-absolute top-50 start-50 translate-middle rounded-4 d-flex justify-content-center p-3 p-md-0"
        content-transition="vfm-fade"
        overlay-transition="vfm-fade"
        overlay-style="backdrop-filter: blur(5px); background-color: #e836c542;"
        :click-to-close="false"
        :esc-to-close="false"
        modal-id="adult-only-modal"
    >
        <div class="d-flex flex-column justify-content-center align-items-center gap-4">
            <h2 class="fs-3 font-default fw-bold text-center color-light">
                {{ $t('modals.are_you_adult') }}
            </h2>
            <p class="fs-5 font-merge color-light">
                {{ $t('modals.adult_only_warning') }}
            </p>
            <div class="d-flex flex-column flex-md-row justify-content-center align-items-center gap-3 gap-md-5 w-100">
                <DefaultLink link="https://google.com/" class-list="w-100 btn-default btn-pink">
                    {{ $t('buttons.not_18') }}
                </DefaultLink>
                <BOverlay :show="processing" rounded="pill" class="w-100">
                    <DefaultButton class-list="w-100 btn-outline" :disabled="processing" @click="accept">
                        {{ $t('buttons.has_18') }}
                    </DefaultButton>
                </BOverlay>
            </div>
        </div>
    </VueFinalModal>
</template>

// frontend/src/Components/Modals/AdultOnlyModal.tsx
import React, { useState } from 'react';
import { Modal, Spinner } from 'react-bootstrap';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import apiClient from '@/api/client';

interface AdultOnlyModalProps {
    show: boolean;
    onClose: () => void;
    onAccepted?: () => void;
}

export default function AdultOnlyModal({ show, onClose, onAccepted }: AdultOnlyModalProps) {
    const [processing, setProcessing] = useState(false);

    const accept = async () => {
        setProcessing(true);
        try {
            await apiClient.post('/terms/accept', { accept: true });
            setProcessing(false);
            onAccepted?.();
        } catch {
            setProcessing(false);
        }
    };

    return (
        <Modal
            show={show}
            onHide={onClose}
            centered
            backdrop="static"
            keyboard={false}
            contentClassName="lightbox-warning-18 rounded-4 d-flex justify-content-center p-3 p-md-0"
        >
            <Modal.Body>
                <div className="d-flex flex-column justify-content-center align-items-center gap-4">
                    <h2 className="fs-3 font-default fw-bold text-center color-light">
                        Are you over 18?
                    </h2>
                    <p className="fs-5 font-merge color-light">
                        This content is for adults only.
                    </p>
                    <div className="d-flex flex-column flex-md-row justify-content-center align-items-center gap-3 gap-md-5 w-100">
                        <a href="https://google.com/" className="btn btn-default btn-pink w-100">
                            I am not 18
                        </a>
                        <div className="w-100 position-relative">
                            {processing && (
                                <div className="position-absolute top-50 start-50 translate-middle">
                                    <Spinner animation="border" variant="danger" />
                                </div>
                            )}
                            <DefaultButton classList="w-100 btn-outline" disabled={processing} onClick={accept}>
                                I am 18 or older
                            </DefaultButton>
                        </div>
                    </div>
                </div>
            </Modal.Body>
        </Modal>
    );
}
