// Afterdarkv2-main/resources/js/Components/Modals/CreatePodcastModal.vue
<script setup>
import { VueFinalModal } from 'vue-final-modal';
import { $t, $td } from '@/i18n.js';
import { BFormCheckbox, BFormInput, BFormTextarea, BFormFile, BOverlay, BSpinner } from 'bootstrap-vue-next';
import { defineAsyncComponent, ref, watch } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import { songAssetImage } from '@/Services/AssetService.js';
import { removeEmptyObjectsKeys, slugify } from '@/Services/FormService.js';
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));

const emit = defineEmits(['close']);

const page = usePage();

const maxAllowed = 60;

const titleLength = ref(0);
const inputAllowed = ref(true);

const tags = ref(page.props.filter_presets.tags);
const categories = ref(page.props.filter_presets.podcast_categories);
const artworkPreview = ref(songAssetImage);
const defaultArtworkPreview = ref(songAssetImage);

const form = useForm({
    title: null,
    tags: [],
    categories: [],
    is_visible: false,
    allow_comments: false,
    allow_download: false,
    explicit: false,
    description: null,
    artwork: null,
    language_id: null,
});

const setImagePreview = () => {
    artworkPreview.value = form.artwork ? URL.createObjectURL(form.artwork) : defaultArtworkPreview.value;
};

const create = () => {
    form.transform(removeEmptyObjectsKeys).post(route('podcasts.store'), {
        preserveState: true,
        preserveScroll: true,
        onSuccess: () => emit('close'),
    });
};

const addTag = (tag) => {
    const newTag = {
        id: -Math.floor(Math.random() * 10000000),
        tag: slugify(tag),
    };

    tags.value.push(newTag);
    form.tags.push(newTag);
};

const close = () => {
    form.reset();
    emit('close');
};

watch(
    () => form.title,
    (newValue) => {
        titleLength.value = newValue?.length ?? 0;
        inputAllowed.value = newValue?.length < maxAllowed;
    },
);
</script>

<template>
    <VueFinalModal
        class="d-flex justify-content-center align-items-center"
        content-class="bg-default position-absolute top-50 start-50 translate-middle rounded-4 d-flex flex-column p-4 max-height-75"
        content-transition="vfm-fade"
        overlay-transition="vfm-fade"
        :click-to-close="!form.processing"
        :esc-to-close="!form.processing"
        modal-id="podcast-create-modal"
    >
        <div class="container-fluid overflow-y-auto">
            <div class="w-100 text-center font-default fs-5 mb-2">
                {{ $t('modals.create_podcast') }}
            </div>
            <BOverlay rounded="sm" :show="form.processing">
                <template #overlay>
                    <div class="d-flex flex-column w-100 text-center align-items-center justify-content-center gap-4">
                        <span class="font-default">{{ $td('misc.please_wait') }}</span>
                        <div class="d-flex flex-row gap-2 align-items-center">
                            <BSpinner variant="danger" />
                            <span class="font-default fw-bold fs-5"> {{ form.progress?.percentage }}% </span>
                        </div>
                    </div>
                </template>
                <div class="row">
                    <div class="col-12 col-xl-4">
                        <div class="d-flex flex-column justify-content-start w-100 gap-4">
                            <div class="d-flex flex-column justify-content-center align-items-start gap-1">
                                <label class="text-center font-default fs-14 default-text-color">
                                    {{ $t('misc.artwork') }}
                                </label>
                                <img
                                    :src="artworkPreview"
                                    class="img-fluid rounded-4 border-pink"
                                    alt="artwork"
                                    ref="imagePreview"
                                />
                            </div>
                            <BFormFile v-model="form.artwork" accept="image/*" @update:model-value="setImagePreview" />
                            <div class="d-flex flex-column fw-light text-secondary text-center font-merge">
                                <span>{{ $t('modals.upload.image_description.line_1') }}</span>
                                <span>{{ $t('modals.upload.image_description.line_2') }}</span>
                                <span>{{ $t('modals.upload.image_description.line_3') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="d-flex flex-column justify-content-start w-100 gap-4">
                            <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label class="text-start font-default fs-14 default-text-color">
                                    {{ $t('misc.title') }}
                                </label>
                                <BFormInput v-model="form.title" type="text" :state="inputAllowed" :max="maxAllowed" />
                                <span
                                    class="fs-12 font-merge color-grey"
                                    :class="{
                                        'color-pink': !inputAllowed,
                                    }"
                                >
                                    {{
                                        $t('modals.upload.characters_allowed', {
                                            max: maxAllowed,
                                            used: titleLength,
                                        })
                                    }}
                                </span>
                            </div>
                            <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label class="text-start font-default fs-14 default-text-color">
                                    {{ $t('misc.tags') }}
                                </label>
                                <vue-multiselect
                                    v-model="form.tags"
                                    :options="tags"
                                    :multiple="true"
                                    :taggable="true"
                                    track-by="id"
                                    label="tag"
                                    @tag="addTag"
                                />
                            </div>
                            <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label class="text-start font-default fs-14 default-text-color">
                                    {{ $t('misc.categories') }}
                                </label>
                                <vue-multiselect
                                    v-model="form.categories"
                                    :options="categories"
                                    :multiple="true"
                                    track-by="id"
                                    label="name"
                                />
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <div class="d-flex flex-column justify-content-start align-items-start">
                                        <BFormCheckbox v-model="form.is_visible" switch>
                                            {{ $t('misc.make_public') }}
                                        </BFormCheckbox>
                                        <BFormCheckbox v-model="form.explicit" switch>
                                            {{ $t('misc.explicit') }}
                                        </BFormCheckbox>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="d-flex flex-column justify-content-start align-items-start">
                                        <BFormCheckbox v-model="form.allow_comments" switch>
                                            {{ $t('misc.allow_comments') }}
                                        </BFormCheckbox>
                                        <BFormCheckbox v-model="form.allow_download" switch>
                                            {{ $t('misc.allow_download') }}
                                        </BFormCheckbox>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label class="text-start font-default fs-14 default-text-color">
                                    {{ $t('misc.description') }}
                                </label>
                                <BFormTextarea v-model="form.description" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row justify-content-center align-items-center w-100 gap-4 mt-4">
                    <DefaultButton class-list="btn-pink" @click="create" :disabled="form.processing">
                        <Icon :icon="['fas', 'floppy-disk']" />
                        {{ $t('buttons.create.title') }}
                    </DefaultButton>
                    <DefaultButton class-list="btn-outline" :disabled="form.processing" @click="close">
                        <Icon :icon="['fas', 'trash']" />
                        {{ $t('buttons.cancel') }}
                    </DefaultButton>
                </div>
            </BOverlay>
        </div>
    </VueFinalModal>
</template>

// frontend/src/Components/Modals/CreatePodcastModal.tsx
import React, { useState, useEffect } from 'react';
import { Modal, Form, Spinner } from 'react-bootstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';

interface CreatePodcastModalProps {
    show: boolean;
    onClose: () => void;
}

export default function CreatePodcastModal({ show, onClose }: CreatePodcastModalProps) {
    const user = useAuthStore((state) => state.user);
    const maxAllowed = 60;

    const [title, setTitle] = useState('');
    const [description, setDescription] = useState('');
    const [isVisible, setIsVisible] = useState(false);
    const [allowComments, setAllowComments] = useState(false);
    const [allowDownload, setAllowDownload] = useState(false);
    const [explicit, setExplicit] = useState(false);
    const [artwork, setArtwork] = useState<File | null>(null);
    const [artworkPreview, setArtworkPreview] = useState('/assets/images/song.png');
    const [processing, setProcessing] = useState(false);
    const [titleLength, setTitleLength] = useState(0);
    const [inputAllowed, setInputAllowed] = useState(true);

    useEffect(() => {
        setTitleLength(title?.length ?? 0);
        setInputAllowed((title?.length ?? 0) < maxAllowed);
    }, [title]);

    useEffect(() => {
        if (artwork) {
            setArtworkPreview(URL.createObjectURL(artwork));
        } else {
            setArtworkPreview('/assets/images/song.png');
        }
    }, [artwork]);

    const create = async () => {
        setProcessing(true);
        try {
            const formData = new FormData();
            formData.append('title', title);
            formData.append('description', description || '');
            formData.append('is_visible', String(isVisible));
            formData.append('allow_comments', String(allowComments));
            formData.append('allow_download', String(allowDownload));
            formData.append('explicit', String(explicit));
            if (artwork) formData.append('artwork', artwork);

            await apiClient.post('/podcasts', formData, {
                headers: { 'Content-Type': 'multipart/form-data' },
            });
            resetForm();
            onClose();
        } catch (err) {
            console.error('Create podcast failed:', err);
        } finally {
            setProcessing(false);
        }
    };

    const resetForm = () => {
        setTitle('');
        setDescription('');
        setIsVisible(false);
        setAllowComments(false);
        setAllowDownload(false);
        setExplicit(false);
        setArtwork(null);
    };

    const close = () => {
        resetForm();
        onClose();
    };

    return (
        <Modal show={show} onHide={onClose} centered size="lg" backdrop={processing ? 'static' : true} keyboard={!processing}>
            <Modal.Body className="d-flex flex-column p-4">
                <div className="container-fluid overflow-y-auto">
                    <div className="w-100 text-center font-default fs-5 mb-2">Create Podcast</div>
                    {processing && (
                        <div className="d-flex flex-column w-100 text-center align-items-center justify-content-center gap-4 my-3">
                            <span className="font-default">Please wait...</span>
                            <Spinner animation="border" variant="danger" />
                        </div>
                    )}
                    <div className="row">
                        <div className="col-12 col-xl-4">
                            <div className="d-flex flex-column justify-content-start w-100 gap-4">
                                <div className="d-flex flex-column justify-content-center align-items-start gap-1">
                                    <label className="text-center font-default fs-14 default-text-color">Artwork</label>
                                    <img src={artworkPreview} className="img-fluid rounded-4 border-pink" alt="artwork" />
                                </div>
                                <Form.Control type="file" accept="image/*" onChange={(e: React.ChangeEvent<HTMLInputElement>) => setArtwork(e.target.files?.[0] || null)} />
                                <div className="d-flex flex-column fw-light text-secondary text-center font-merge">
                                    <span>Recommended size: 500x500px</span>
                                    <span>Max file size: 2MB</span>
                                    <span>Formats: JPG, PNG</span>
                                </div>
                            </div>
                        </div>
                        <div className="col">
                            <div className="d-flex flex-column justify-content-start w-100 gap-4">
                                <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                    <label className="text-start font-default fs-14 default-text-color">Title</label>
                                    <Form.Control
                                        type="text"
                                        value={title}
                                        onChange={(e) => setTitle(e.target.value)}
                                        isValid={inputAllowed}
                                        isInvalid={!inputAllowed}
                                        maxLength={maxAllowed}
                                    />
                                    <span className={`fs-12 font-merge ${!inputAllowed ? 'color-pink' : 'color-grey'}`}>
                                        {titleLength}/{maxAllowed} characters
                                    </span>
                                </div>
                                <div className="row">
                                    <div className="col-6">
                                        <div className="d-flex flex-column justify-content-start align-items-start">
                                            <Form.Check type="switch" label="Make Public" checked={isVisible} onChange={(e) => setIsVisible(e.target.checked)} />
                                            <Form.Check type="switch" label="Explicit" checked={explicit} onChange={(e) => setExplicit(e.target.checked)} />
                                        </div>
                                    </div>
                                    <div className="col-6">
                                        <div className="d-flex flex-column justify-content-start align-items-start">
                                            <Form.Check type="switch" label="Allow Comments" checked={allowComments} onChange={(e) => setAllowComments(e.target.checked)} />
                                            <Form.Check type="switch" label="Allow Download" checked={allowDownload} onChange={(e) => setAllowDownload(e.target.checked)} />
                                        </div>
                                    </div>
                                </div>
                                <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                    <label className="text-start font-default fs-14 default-text-color">Description</label>
                                    <Form.Control as="textarea" value={description} onChange={(e) => setDescription(e.target.value)} />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="d-flex flex-row justify-content-center align-items-center w-100 gap-4 mt-4">
                        <DefaultButton classList="btn-pink" onClick={create} disabled={processing}>
                            <FontAwesomeIcon icon={['fas', 'floppy-disk']} /> Create
                        </DefaultButton>
                        <DefaultButton classList="btn-outline" disabled={processing} onClick={close}>
                            <FontAwesomeIcon icon={['fas', 'trash']} /> Cancel
                        </DefaultButton>
                    </div>
                </div>
            </Modal.Body>
        </Modal>
    );
}
