// frontend/src/Components/Modals/FeedbackModal.tsx
import React, { useState, useEffect } from 'react';
import { Modal, Form } from 'react-bootstrap';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';

interface FeedbackModalProps {
    show: boolean;
    onClose: () => void;
}

export default function FeedbackModal({ show, onClose }: FeedbackModalProps) {
    const user = useAuthStore((state) => state.user);
    const [email, setEmail] = useState('');
    const [emotion, setEmotion] = useState('');
    const [about, setAbout] = useState('');
    const [message, setMessage] = useState('');

    const emotions = ['Angry', 'Confused', 'Happy', 'Amused', 'Impressed', 'Surprised', 'Disappointed', 'Frustrated', 'Curious', 'Indifferent'];
    const aboutOptions = [
        { value: 'Website', label: 'Website' },
        { value: 'General', label: 'General Questions' },
        { value: 'iPhone', label: 'iPhone' },
        { value: 'Android', label: 'Android' },
    ];

    useEffect(() => {
        if (user?.email) {
            setEmail(user.email);
        }
    }, [user]);

    const submit = () => {
        onClose();
    };

    const cancel = () => {
        setEmail(user?.email || '');
        setEmotion('');
        setAbout('');
        setMessage('');
        onClose();
    };

    return (
        <Modal show={show} onHide={onClose} centered>
            <Modal.Body className="d-flex flex-column p-3 p-md-5">
                <div className="text-center font-default fs-5">Feedback</div>
                <p className="font-default fs-14">We would love to hear your thoughts!</p>
                <div className="container-fluid">
                    <div className="row gy-3 gy-lg-4">
                        <div className="col-12">
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label className="font-default fs-14 default-text-color">Email</label>
                                <Form.Control type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
                            </div>
                        </div>
                        <div className="col-12 col-lg-6">
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label className="font-default fs-14 default-text-color">I feel:</label>
                                <Form.Select value={emotion} onChange={(e) => setEmotion(e.target.value)}>
                                    <option value="">Select...</option>
                                    {emotions.map((em) => (
                                        <option key={em} value={em}>{em}</option>
                                    ))}
                                </Form.Select>
                            </div>
                        </div>
                        <div className="col-12 col-lg-6">
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label className="font-default fs-14 default-text-color">Feedback about:</label>
                                <Form.Select value={about} onChange={(e) => setAbout(e.target.value)}>
                                    <option value="">Select...</option>
                                    {aboutOptions.map((opt) => (
                                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                                    ))}
                                </Form.Select>
                            </div>
                        </div>
                        <div className="col-12">
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                <label className="font-default fs-14 default-text-color">Share your thoughts</label>
                                <Form.Control
                                    as="textarea"
                                    rows={3}
                                    value={message}
                                    onChange={(e) => setMessage(e.target.value)}
                                    placeholder="Share your thoughts"
                                />
                            </div>
                        </div>
                    </div>
                    <div className="d-flex flex-row justify-content-between align-items-center mt-5 w-100">
                        <DefaultButton classList="btn-outline" onClick={cancel}>Cancel</DefaultButton>
                        <DefaultButton classList="btn-pink" onClick={submit}>Submit</DefaultButton>
                    </div>
                </div>
            </Modal.Body>
        </Modal>
    );
}

// frontend/src/Components/Modals/FeedbackModal.vue
<script setup>
import { useVfm, VueFinalModal } from 'vue-final-modal';
import { $t } from '@/i18n.js';
import { BInput, BFormSelect, BFormTextarea } from 'bootstrap-vue-next';
import { defineAsyncComponent, onMounted, ref, reactive } from 'vue';
import { useForm } from '@/helpers/useForm'
import apiClient from '@/api/client'
import { useAuthStore } from '@/stores/auth'
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));

const vfm = useVfm();
const emit = defineEmits(['cancel']);

const form = useForm({
    email: '',
    emotion: null,
    about: null,
    message: '',
});

const emotions = ref([
    'Angry',
    'Confused',
    'Happy',
    'Amused',
    'Impressed',
    'Surprised',
    'Disappointed',
    'Frustrated',
    'Curious',
    'Indifferent',
]);

const about = ref([
    { value: 'Website', text: 'Website' },
    { value: 'General', text: 'General Questions' },
    {
        label: 'Mobile Devices',
        options: [
            { value: 'iPhone', text: 'iPhone' },
            { value: 'Android', text: 'Android' },
        ],
    },
]);

const submit = () => {
    emit('cancel');
    vfm.close('feedback-modal');
    // apiClient.post('', form);
};

const cancel = () => {
    form.reset();
    emit('cancel');
    vfm.close('feedback-modal');
};

onMounted(() => {
    form.email = useAuthStore().user?.email;
});
</script>

<template>
    <VueFinalModal
        class="d-flex justify-content-center align-items-center gap-3 w-100"
        content-class="bg-default position-absolute top-50 start-50 translate-middle rounded-4 d-flex flex-column p-3 p-md-5"
        content-transition="vfm-fade"
        overlay-transition="vfm-fade"
        modal-id="feedback-modal"
    >
        <div class="text-center font-default fs-5">
            {{ $t('modals.feedback') }}
        </div>
        <p class="font-default fs-14">
            {{ $t('modals.feedback_message') }}
        </p>
        <div class="container-fluid">
            <div class="row gy-3 gy-lg-4">
                <div class="col-12">
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                        <label
                            for="email"
                            class="font-default fs-14 default-text-color"
                            data-translate-text="LB_FEEDBACK_EMAIL"
                        >
                            {{ $t('misc.email') }}
                        </label>
                        <BInput type="email" v-model="form.email" required />
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                        <label
                            for="feedback_feeling"
                            class="font-default fs-14 default-text-color"
                            data-translate-text="LB_FEEDBACK_FEELING"
                        >
                            {{ $t('modals.i_feel') }}:
                        </label>
                        <BFormSelect :options="emotions" v-model="form.emotion" />
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                        <label
                            for="feedback_about"
                            class="font-default fs-14 default-text-color"
                            data-translate-text="LB_FEEDBACK_ABOUT"
                        >
                            {{ $t('modals.feedback_about') }}:
                        </label>
                        <BFormSelect :options="about" v-model="form.about" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                        <label
                            for="comment"
                            class="font-default fs-14 default-text-color"
                            data-translate-text="LB_FEEDBACK_REPORT"
                        >
                            {{ $t('modals.share_thoughts') }}
                        </label>
                        <BFormTextarea v-model="form.message" :placeholder="$t('modals.share_thoughts')" rows="3" />
                    </div>
                </div>
            </div>
            <div class="d-flex flex-row justify-content-between align-items-center mt-5 w-100">
                <DefaultButton class-list="btn-outline" @click="cancel">
                    {{ $t('buttons.cancel') }}
                </DefaultButton>
                <DefaultButton class-list="btn-pink" @click="submit">
                    {{ $t('buttons.submit') }}
                </DefaultButton>
            </div>
        </div>
    </VueFinalModal>
</template>

<style scoped></style>
