// frontend/src/Components/Modals/PodcastEpisodeUploadModal.vue
<script setup>
import { VueFinalModal } from 'vue-final-modal';
import { $t, $td } from '@/i18n.js';
import {
    BFormCheckbox,
    BFormInput,
    BFormSelect,
    BFormTextarea,
    BFormFile,
    BOverlay,
    BSpinner,
    BTabs,
    BTab,
} from 'bootstrap-vue-next';
import { computed, defineAsyncComponent, ref, watch, reactive } from 'vue';
import { useForm } from '@/helpers/useForm'
import apiClient from '@/api/client'
import { useAuthStore } from '@/stores/auth'
import { parseBlob } from 'music-metadata';
import { songAssetImage } from '@/Services/AssetService.js';
import { removeEmptyObjectsKeys } from '@/Services/FormService.js';
const Icon = defineAsyncComponent(() => import('@/Components/Icons/Icon.vue'));
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));
const IconButton = defineAsyncComponent(() => import('@/Components/Buttons/IconButton.vue'));
import route from "@/helpers/route"

const emit = defineEmits(['close']);

const authStore = useAuthStore();
const user = authStore.user;

const allowedFileSize = 92970;
const maxAllowed = 60;

const titleLength = ref(0);
const inputAllowed = ref(true);
const seasonAdded = ref(false);

const tabIndex = ref(0);

const hasFile = ref(false);
const podcastDataSelected = ref(false);
const validateFileSize = ref(false);
const artworkPreview = ref(songAssetImage);
const defaultArtworkPreview = ref(songAssetImage);
const seasonOptions = ref([]);
const episodeNumberOptions = ref([]);

const form = useForm({
    title: null,
    season: null,
    number: null,
    is_visible: false,
    allow_comments: false,
    allow_download: false,
    explicit: false,
    description: null,
    file: null,
    artwork: null,
    podcast_uuid: null,
});

const setId3Data = (data) => {
    if (!data) {
        return;
    }

    parseBlob(data).then((tags) => {
        form.title = tags.common.title ? tags.common.title : data.name;

        if (tags.common.picture?.length) {
            const blob = new Blob([tags.common.picture[0].data], {
                type: tags.common.picture[0].format,
            });

            defaultArtworkPreview.value = URL.createObjectURL(blob);
            artworkPreview.value = defaultArtworkPreview.value;
        } else {
            defaultArtworkPreview.value = songAssetImage;
            artworkPreview.value = songAssetImage;
        }
    });
};

const setImagePreview = () => {
    artworkPreview.value = form.artwork ? URL.createObjectURL(form.artwork) : defaultArtworkPreview.value;
};

const upload = () => {
    form.transform(removeEmptyObjectsKeys).post(route('upload.episodes.store'), {
        preserveState: true,
        preserveScroll: true,
        onSuccess: () => close(),
    });
};

const close = () => {
    form.reset();
    emit('close');
};

const proceed = () => {
    tabIndex.value = 1;
};

const addSeason = () => {
    if (form.podcast_uuid) {
        const podcast = user.podcasts.find((podcast) => podcast.uuid === form.podcast_uuid);

        if (!podcast) {
            return;
        }

        seasonOptions.value = Array.from({ length: podcast.seasons + 1 }, (_, i) => ({
            value: i + 1,
            text: `Season ${i + 1}`,
        }));

        episodeNumberOptions.value = Array.from({ length: 1 }, (_, i) => ({
            value: i + 1,
            text: `Episode ${i + 1}`,
        }));

        form.season = podcast.seasons + 1;
        form.number = 0;

        seasonAdded.value = true;
    }
};

const validatePodcastSelection = () =>
    (podcastDataSelected.value = !!form.podcast_uuid && !!form.season && !!form.number);

const podcasts = computed(() => {
    if (user.podcasts.length) {
        return user.podcasts.map((podcast) => {
            return {
                value: podcast.uuid,
                text: podcast.title,
            };
        });
    }

    return [];
});

watch(
    () => form.title,
    (newValue) => {
        titleLength.value = newValue?.length ?? 0;
        inputAllowed.value = newValue?.length < maxAllowed;
    },
);

watch(
    () => form.file,
    (newValue) => {
        const isEmpty = !newValue || newValue.size <= 0;
        validateFileSize.value = isEmpty ? false : Math.round(newValue.size / 1024) <= allowedFileSize;
        hasFile.value = !isEmpty && validateFileSize.value;
    },
);

watch(
    () => form.podcast_uuid,
    (newValue) => {
        if (!newValue) {
            return;
        }

        const podcast = user.podcasts.find((podcast) => podcast.uuid === newValue);

        if (!podcast) {
            return;
        }

        seasonOptions.value = Array.from({ length: podcast.seasons }, (_, i) => ({
            value: i + 1,
            text: `Season ${i + 1}`,
        }));

        seasonAdded.value = false;
        form.number = null;
        form.season = null;

        validatePodcastSelection();
    },
);

watch(
    () => form.season,
    (newValue) => {
        const podcast = user.podcasts.find((podcast) => podcast.uuid === form.podcast_uuid);

        if (!podcast) {
            return;
        }

        const season = podcast.details.find((season) => season.season === newValue);

        if (!season) {
            episodeNumberOptions.value = Array.from({ length: 1 }, (_, i) => ({
                value: i + 1,
                text: $t('modals.upload.podcast.season', { index: i + 1 }),
            }));
        } else {
            episodeNumberOptions.value = Array.from({ length: season.episodes + 1 }, (_, i) => ({
                value: i + 1,
                text: $t('modals.upload.podcast.episode', { index: i + 1 }),
                disabled: i < season.episodes,
            }));
        }

        form.number = 0;

        validatePodcastSelection();
    },
);

watch(
    () => form.number,
    (newValue) => {
        if (!newValue) {
            return;
        }

        validatePodcastSelection();
    },
);
</script>

<template>
    <VueFinalModal
        class="d-flex justify-content-center align-items-center"
        content-class="bg-default position-absolute top-50 start-50 translate-middle rounded-4 d-flex flex-column p-4 max-height-75"
        content-transition="vfm-fade"
        overlay-transition="vfm-fade"
        :click-to-close="!form.processing"
        :esc-to-close="!form.processing"
        modal-id="podcast-upload-modal"
    >
        <div class="container-fluid overflow-y-auto">
            <div class="w-100 text-center font-default fs-5 mb-2">
                {{ $t('modals.upload.podcast.title') }}
            </div>
            <BOverlay rounded="sm" :show="form.processing">
                <template #overlay>
                    <div class="d-flex flex-column w-100 text-center align-items-center justify-content-center gap-4">
                        <span class="font-default">{{ $td('misc.please_wait') }}</span>
                        <div class="d-flex flex-row gap-2 align-items-center">
                            <BSpinner variant="danger" />
                            <span class="font-default fw-bold fs-5"> {{ form.progress?.percentage }}% </span>
                        </div>
                    </div>
                </template>
                <BTabs
                    nav-wrapper-class="tabs-header w-100"
                    nav-class="tab-item px-4 d-flex"
                    active-nav-item-class="tab-item-active"
                    tab-class="py-3"
                    nav-item-class="tab-item default-text-color px-4"
                    content-class="overflow-x-hidden"
                    v-model="tabIndex"
                    fill
                >
                    <BTab :title="$t('modals.upload.podcast.select')" :disabled="tabIndex === 1">
                        <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                            <label class="text-start font-default fs-14 default-text-color">
                                {{ $t('misc.podcast') }}
                            </label>
                            <BFormSelect v-model="form.podcast_uuid" :options="podcasts" />
                        </div>
                        <div class="row mt-4">
                            <div class="col-6 d-flex flex-column justify-content-end align-items-start gap-1">
                                <label
                                    class="text-start font-default fs-14 default-text-color d-flex flex-row align-items-center"
                                >
                                    <span>{{ $t('misc.season') }}</span>
                                    <IconButton
                                        icon="plus"
                                        :disabled="!form.podcast_uuid || seasonAdded"
                                        @click="addSeason"
                                        class-list="btn-pink btn-sm"
                                    />
                                </label>
                                <BFormSelect
                                    v-model="form.season"
                                    :options="seasonOptions"
                                    :disabled="!form.podcast_uuid"
                                    required
                                />
                            </div>
                            <div class="col-6 d-flex flex-column justify-content-end align-items-start gap-1">
                                <label class="text-start font-default fs-14 default-text-color">
                                    {{ $t('misc.episode_number') }}
                                </label>
                                <BFormSelect
                                    v-model="form.number"
                                    :options="episodeNumberOptions"
                                    :disabled="!form.podcast_uuid"
                                    required
                                />
                            </div>
                        </div>
                        <div class="d-flex flex-row justify-content-center align-items-center w-100 gap-4 mt-4">
                            <DefaultButton
                                class-list="btn-pink"
                                @click="proceed"
                                :disabled="form.processing || !podcastDataSelected"
                            >
                                <Icon :icon="['fas', 'angles-right']" />
                                {{ $t('buttons.proceed') }}
                            </DefaultButton>
                            <DefaultButton class-list="btn-outline" :disabled="form.processing" @click="close">
                                <Icon :icon="['fas', 'trash']" />
                                {{ $t('buttons.cancel') }}
                            </DefaultButton>
                        </div>
                    </BTab>
                    <BTab :title="$t('modals.upload.input_details')" :disabled="!podcastDataSelected">
                        <div class="d-flex flex-column w-100 gap-4">
                            <div class="d-flex flex-column justify-content-center align-items-start gap-1 w-100">
                                <label class="text-center font-default fs-14 default-text-color">
                                    {{ $t('misc.select_file') }}
                                </label>
                                <BFormFile
                                    v-model="form.file"
                                    accept="audio/*"
                                    :state="validateFileSize"
                                    @update:model-value="setId3Data"
                                />
                            </div>
                            <div class="row">
                                <div class="col-12 col-xl-4 d-flex flex-column justify-content-start gap-4">
                                    <div class="d-flex flex-column justify-content-center align-items-start gap-1">
                                        <label class="text-center font-default fs-14 default-text-color">
                                            {{ $t('misc.artwork') }}
                                        </label>
                                        <img
                                            :src="artworkPreview"
                                            class="img-fluid rounded-4 border-pink"
                                            alt="artwork"
                                            ref="imagePreview"
                                        />
                                    </div>
                                    <BFormFile
                                        v-model="form.artwork"
                                        accept="image/*"
                                        @update:model-value="setImagePreview"
                                    />
                                    <div class="d-flex flex-column fw-light text-secondary text-center font-merge">
                                        <span>{{ $t('modals.upload.image_description.line_1') }}</span>
                                        <span>{{ $t('modals.upload.image_description.line_2') }}</span>
                                        <span>{{ $t('modals.upload.image_description.line_3') }}</span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="d-flex flex-column justify-content-start w-100 gap-4">
                                        <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                                            <label class="text-start font-default fs-14 default-text-color">
                                                {{ $t('misc.title') }}
                                            </label>
                                            <BFormInput
                                                v-model="form.title"
                                                type="text"
                                                :state="inputAllowed"
                                                :max="maxAllowed"
                                            />
                                            <span
                                                class="fs-12 font-merge color-grey"
                                                :class="{
                                                    'color-pink': !inputAllowed,
                                                }"
                                            >
                                                {{
                                                    $t('modals.upload.characters_allowed', {
                                                        max: maxAllowed,
                                                        used: titleLength,
                                                    })
                                                }}
                                            </span>
                                        </div>
                                        <div class="row">
                                            <div class="col-6">
                                                <div class="d-flex flex-column justify-content-start align-items-start">
                                                    <BFormCheckbox v-model="form.is_visible" switch>
                                                        {{ $t('misc.make_public') }}
                                                    </BFormCheckbox>
                                                    <BFormCheckbox v-model="form.explicit" switch>
                                                        {{ $t('misc.explicit') }}
                                                    </BFormCheckbox>
                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <div class="d-flex flex-column justify-content-start align-items-start">
                                                    <BFormCheckbox v-model="form.allow_comments" switch>
                                                        {{ $t('misc.allow_comments') }}
                                                    </BFormCheckbox>
                                                    <BFormCheckbox v-model="form.allow_download" switch>
                                                        {{ $t('misc.allow_download') }}
                                                    </BFormCheckbox>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="d-flex flex-column justify-content-start align-items-start gap-1">
                                            <label class="text-start font-default fs-14 default-text-color">
                                                {{ $t('misc.description') }}
                                            </label>
                                            <BFormTextarea v-model="form.description" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex flex-row justify-content-center align-items-center w-100 gap-4">
                                <DefaultButton
                                    class-list="btn-pink"
                                    @click="upload"
                                    :disabled="form.processing || !hasFile"
                                >
                                    <Icon :icon="['fas', 'floppy-disk']" />
                                    {{ $t('buttons.upload.default') }}
                                </DefaultButton>
                                <DefaultButton class-list="btn-outline" :disabled="form.processing" @click="close">
                                    <Icon :icon="['fas', 'trash']" />
                                    {{ $t('buttons.cancel') }}
                                </DefaultButton>
                            </div>
                        </div>
                    </BTab>
                </BTabs>
            </BOverlay>
        </div>
    </VueFinalModal>
</template>

// frontend/src/Components/Modals/PodcastEpisodeUploadModal.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { Modal, Form, Spinner, Tab, Tabs } from 'react-bootstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import DefaultButton from '@/Components/Buttons/DefaultButton';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/auth';

interface PodcastEpisodeUploadModalProps {
    show: boolean;
    onClose: () => void;
}

export default function PodcastEpisodeUploadModal({ show, onClose }: PodcastEpisodeUploadModalProps) {
    const user = useAuthStore((state) => state.user);
    const allowedFileSize = 92970;
    const maxAllowed = 60;

    const [title, setTitle] = useState('');
    const [description, setDescription] = useState('');
    const [isVisible, setIsVisible] = useState(false);
    const [allowComments, setAllowComments] = useState(false);
    const [allowDownload, setAllowDownload] = useState(false);
    const [explicit, setExplicit] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const [artwork, setArtwork] = useState<File | null>(null);
    const [artworkPreview, setArtworkPreview] = useState('/assets/images/song.png');
    const [podcastUuid, setPodcastUuid] = useState('');
    const [season, setSeason] = useState<number | null>(null);
    const [episodeNumber, setEpisodeNumber] = useState<number | null>(null);
    const [hasFile, setHasFile] = useState(false);
    const [validateFileSize, setValidateFileSize] = useState(false);
    const [processing, setProcessing] = useState(false);
    const [progress, setProgress] = useState(0);
    const [titleLength, setTitleLength] = useState(0);
    const [inputAllowed, setInputAllowed] = useState(true);
    const [activeTab, setActiveTab] = useState('select');
    const [podcastDataSelected, setPodcastDataSelected] = useState(false);
    const [seasonOptions, setSeasonOptions] = useState<any[]>([]);
    const [episodeNumberOptions, setEpisodeNumberOptions] = useState<any[]>([]);
    const [seasonAdded, setSeasonAdded] = useState(false);

    useEffect(() => {
        setTitleLength(title?.length ?? 0);
        setInputAllowed((title?.length ?? 0) < maxAllowed);
    }, [title]);

    useEffect(() => {
        if (file) {
            const isEmpty = !file || file.size <= 0;
            const valid = isEmpty ? false : Math.round(file.size / 1024) <= allowedFileSize;
            setValidateFileSize(valid);
            setHasFile(!isEmpty && valid);
        } else {
            setValidateFileSize(false);
            setHasFile(false);
        }
    }, [file]);

    useEffect(() => {
        if (artwork) {
            setArtworkPreview(URL.createObjectURL(artwork));
        } else {
            setArtworkPreview('/assets/images/song.png');
        }
    }, [artwork]);

    useEffect(() => {
        if (!podcastUuid || !user?.podcasts) return;
        const podcast = user.podcasts.find((p: any) => p.uuid === podcastUuid);
        if (!podcast) return;
        setSeasonOptions(
            Array.from({ length: podcast.seasons }, (_, i) => ({ value: i + 1, text: `Season ${i + 1}` }))
        );
        setSeasonAdded(false);
        setSeason(null);
        setEpisodeNumber(null);
        validateSelection();
    }, [podcastUuid]);

    useEffect(() => {
        validateSelection();
    }, [podcastUuid, season, episodeNumber]);

    const validateSelection = () => {
        setPodcastDataSelected(!!podcastUuid && !!season && !!episodeNumber);
    };

    const podcasts = useMemo(() => {
        if (user?.podcasts?.length) {
            return user.podcasts.map((podcast: any) => ({
                value: podcast.uuid,
                text: podcast.title,
            }));
        }
        return [];
    }, [user]);

    const addSeason = () => {
        if (!podcastUuid || !user?.podcasts) return;
        const podcast = user.podcasts.find((p: any) => p.uuid === podcastUuid);
        if (!podcast) return;
        setSeasonOptions(
            Array.from({ length: podcast.seasons + 1 }, (_, i) => ({ value: i + 1, text: `Season ${i + 1}` }))
        );
        setSeason(podcast.seasons + 1);
        setEpisodeNumber(0);
        setSeasonAdded(true);
    };

    const upload = async () => {
        setProcessing(true);
        try {
            const formData = new FormData();
            formData.append('title', title);
            formData.append('description', description || '');
            formData.append('is_visible', String(isVisible));
            formData.append('allow_comments', String(allowComments));
            formData.append('allow_download', String(allowDownload));
            formData.append('explicit', String(explicit));
            formData.append('podcast_uuid', podcastUuid);
            if (season) formData.append('season', String(season));
            if (episodeNumber) formData.append('number', String(episodeNumber));
            if (file) formData.append('file', file);
            if (artwork) formData.append('artwork', artwork);

            await apiClient.post('/upload/episodes', formData, {
                headers: { 'Content-Type': 'multipart/form-data' },
                onUploadProgress: (e) => {
                    if (e.total) setProgress(Math.round((e.loaded * 100) / e.total));
                },
            });
            close();
        } catch (err) {
            console.error('Upload failed:', err);
        } finally {
            setProcessing(false);
        }
    };

    const close = () => {
        setTitle('');
        setDescription('');
        setFile(null);
        setArtwork(null);
        setPodcastUuid('');
        setSeason(null);
        setEpisodeNumber(null);
        setActiveTab('select');
        setProcessing(false);
        setProgress(0);
        onClose();
    };

    const proceed = () => setActiveTab('details');

    return (
        <Modal show={show} onHide={close} centered size="lg" backdrop={processing ? 'static' : true} keyboard={!processing}>
            <Modal.Body>
                <div className="container-fluid overflow-y-auto">
                    <div className="w-100 text-center font-default fs-5 mb-2">Upload Podcast Episode</div>
                    {processing && (
                        <div className="d-flex flex-column w-100 text-center align-items-center justify-content-center gap-4 my-3">
                            <span className="font-default">Please wait...</span>
                            <div className="d-flex flex-row gap-2 align-items-center">
                                <Spinner animation="border" variant="danger" />
                                <span className="font-default fw-bold fs-5">{progress}%</span>
                            </div>
                        </div>
                    )}
                    <Tabs activeKey={activeTab} onSelect={(k) => k && setActiveTab(k)} className="tabs-header w-100" fill>
                        <Tab eventKey="select" title="Select Podcast" disabled={activeTab === 'details'}>
                            <div className="d-flex flex-column justify-content-start align-items-start gap-1 pt-3">
                                <label className="text-start font-default fs-14 default-text-color">Podcast</label>
                                <Form.Select value={podcastUuid} onChange={(e) => setPodcastUuid(e.target.value)}>
                                    <option value="">Select podcast...</option>
                                    {podcasts.map((p: any) => (
                                        <option key={p.value} value={p.value}>{p.text}</option>
                                    ))}
                                </Form.Select>
                            </div>
                            <div className="row mt-4">
                                <div className="col-6 d-flex flex-column justify-content-end align-items-start gap-1">
                                    <label className="text-start font-default fs-14 default-text-color d-flex flex-row align-items-center">
                                        <span>Season</span>
                                        <button
                                            className="btn btn-sm btn-default btn-pink ms-2"
                                            disabled={!podcastUuid || seasonAdded}
                                            onClick={addSeason}
                                        >
                                            <FontAwesomeIcon icon={['fas', 'plus']} />
                                        </button>
                                    </label>
                                    <Form.Select
                                        value={season || ''}
                                        onChange={(e) => setSeason(Number(e.target.value))}
                                        disabled={!podcastUuid}
                                    >
                                        <option value="">Select season...</option>
                                        {seasonOptions.map((s: any) => (
                                            <option key={s.value} value={s.value}>{s.text}</option>
                                        ))}
                                    </Form.Select>
                                </div>
                                <div className="col-6 d-flex flex-column justify-content-end align-items-start gap-1">
                                    <label className="text-start font-default fs-14 default-text-color">Episode Number</label>
                                    <Form.Select
                                        value={episodeNumber || ''}
                                        onChange={(e) => setEpisodeNumber(Number(e.target.value))}
                                        disabled={!podcastUuid}
                                    >
                                        <option value="">Select...</option>
                                        {episodeNumberOptions.map((ep: any) => (
                                            <option key={ep.value} value={ep.value} disabled={ep.disabled}>{ep.text}</option>
                                        ))}
                                    </Form.Select>
                                </div>
                            </div>
                            <div className="d-flex flex-row justify-content-center align-items-center w-100 gap-4 mt-4">
                                <DefaultButton classList="btn-pink" onClick={proceed} disabled={processing || !podcastDataSelected}>
                                    <FontAwesomeIcon icon={['fas', 'angles-right']} /> Proceed
                                </DefaultButton>
                                <DefaultButton classList="btn-outline" disabled={processing} onClick={close}>
                                    <FontAwesomeIcon icon={['fas', 'trash']} /> Cancel
                                </DefaultButton>
                            </div>
                        </Tab>
                        <Tab eventKey="details" title="Input Details" disabled={!podcastDataSelected}>
                            <div className="d-flex flex-column w-100 gap-4 pt-3">
                                <div className="d-flex flex-column justify-content-center align-items-start gap-1 w-100">
                                    <label className="text-center font-default fs-14 default-text-color">Select File</label>
                                    <Form.Control type="file" accept="audio/*" onChange={(e: React.ChangeEvent<HTMLInputElement>) => setFile(e.target.files?.[0] || null)} />
                                </div>
                                <div className="row">
                                    <div className="col-12 col-xl-4 d-flex flex-column justify-content-start gap-4">
                                        <div className="d-flex flex-column justify-content-center align-items-start gap-1">
                                            <label className="text-center font-default fs-14 default-text-color">Artwork</label>
                                            <img src={artworkPreview} className="img-fluid rounded-4 border-pink" alt="artwork" />
                                        </div>
                                        <Form.Control type="file" accept="image/*" onChange={(e: React.ChangeEvent<HTMLInputElement>) => setArtwork(e.target.files?.[0] || null)} />
                                    </div>
                                    <div className="col">
                                        <div className="d-flex flex-column justify-content-start w-100 gap-4">
                                            <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                                <label className="text-start font-default fs-14 default-text-color">Title</label>
                                                <Form.Control type="text" value={title} onChange={(e) => setTitle(e.target.value)} maxLength={maxAllowed} />
                                                <span className={`fs-12 font-merge ${!inputAllowed ? 'color-pink' : 'color-grey'}`}>
                                                    {titleLength}/{maxAllowed} characters
                                                </span>
                                            </div>
                                            <div className="row">
                                                <div className="col-6">
                                                    <Form.Check type="switch" label="Make Public" checked={isVisible} onChange={(e) => setIsVisible(e.target.checked)} />
                                                    <Form.Check type="switch" label="Explicit" checked={explicit} onChange={(e) => setExplicit(e.target.checked)} />
                                                </div>
                                                <div className="col-6">
                                                    <Form.Check type="switch" label="Allow Comments" checked={allowComments} onChange={(e) => setAllowComments(e.target.checked)} />
                                                    <Form.Check type="switch" label="Allow Download" checked={allowDownload} onChange={(e) => setAllowDownload(e.target.checked)} />
                                                </div>
                                            </div>
                                            <div className="d-flex flex-column justify-content-start align-items-start gap-1">
                                                <label className="text-start font-default fs-14 default-text-color">Description</label>
                                                <Form.Control as="textarea" value={description} onChange={(e) => setDescription(e.target.value)} />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="d-flex flex-row justify-content-center align-items-center w-100 gap-4">
                                    <DefaultButton classList="btn-pink" onClick={upload} disabled={processing || !hasFile}>
                                        <FontAwesomeIcon icon={['fas', 'floppy-disk']} /> Upload
                                    </DefaultButton>
                                    <DefaultButton classList="btn-outline" disabled={processing} onClick={close}>
                                        <FontAwesomeIcon icon={['fas', 'trash']} /> Cancel
                                    </DefaultButton>
                                </div>
                            </div>
                        </Tab>
                    </Tabs>
                </div>
            </Modal.Body>
        </Modal>
    );
}
