// Afterdarkv2-main/resources/js/Components/Modals/SubscriptionModal.vue
<script setup>
import { VueFinalModal } from 'vue-final-modal';
import { $t } from '@/i18n.js';
import { defineAsyncComponent } from 'vue';
const DefaultButton = defineAsyncComponent(() => import('@/Components/Buttons/DefaultButton.vue'));

const emit = defineEmits(['close']);
</script>

<template>
    <VueFinalModal
        class="d-flex justify-content-center align-items-center"
        content-class="bg-default position-absolute top-50 start-50 translate-middle rounded-4 d-flex flex-column p-3 p-md-5"
        content-transition="vfm-fade"
        overlay-transition="vfm-fade"
        modal-id="subscription-modal"
    >
        <div class="text-center font-default fs-5">
            {{ $t('modals.subscription.title') }}
        </div>
        <p class="font-default fs-14">
            {{ $t('modals.subscription.description') }}
        </p>
        <p class="font-default fs-6">
            {{ $t('modals.subscription.message') }}
        </p>
        <div class="d-flex flex-row justify-content-end align-items-center mt-5 w-100">
            <DefaultButton class-list="btn-pink" :href="route('settings.subscription.edit')">
                {{ $t('buttons.subscribe') }}
            </DefaultButton>
        </div>
    </VueFinalModal>
</template>

// frontend/src/Components/Modals/SubscriptionModal.tsx
import React from 'react';
import { Modal } from 'react-bootstrap';
import DefaultButton from '@/Components/Buttons/DefaultButton';

interface SubscriptionModalProps {
    show: boolean;
    onClose: () => void;
}

export default function SubscriptionModal({ show, onClose }: SubscriptionModalProps) {
    return (
        <Modal show={show} onHide={onClose} centered>
            <Modal.Body className="d-flex flex-column p-3 p-md-5">
                <div className="text-center font-default fs-5">Subscription</div>
                <p className="font-default fs-14">
                    This feature requires a subscription.
                </p>
                <p className="font-default fs-6">
                    Subscribe to unlock premium features.
                </p>
                <div className="d-flex flex-row justify-content-end align-items-center mt-5 w-100">
                    <a href="/settings/subscription" className="btn btn-default btn-pink">Subscribe</a>
                </div>
            </Modal.Body>
        </Modal>
    );
}
