// frontend/src/Components/Modals/InviteCollaboratorsModal.tsx
import React from 'react';
import { Modal } from 'react-bootstrap';
import apiClient from '@/api/client';

interface InviteCollaboratorsModalProps {
    show: boolean;
    onClose: () => void;
    playlist_uuid: string;
    following?: any[];
}

export default function InviteCollaboratorsModal({ show, onClose, playlist_uuid, following = [] }: InviteCollaboratorsModalProps) {
    const submit = (user: any) => {
        apiClient.post(`/playlists/${playlist_uuid}/collaborators`, {
            collaborator_uuid: user.uuid,
        });
    };

    return (
        <Modal show={show} onHide={onClose} centered>
            <Modal.Body className="d-flex flex-column p-4">
                <div className="text-center font-default fs-5 mb-3">
                    Invite Collaborators
                </div>
                <div className="row w-100 playlist-container overflow-y-auto">
                    {following.map((user: any) => (
                        <div key={user.uuid} className="col-12 d-flex justify-content-between align-items-center p-2 border-bottom">
                            <span>{user.name || user.username}</span>
                            <button className="btn btn-sm btn-default btn-pink" onClick={() => submit(user)}>
                                Invite
                            </button>
                        </div>
                    ))}
                </div>
            </Modal.Body>
        </Modal>
    );
}

// Afterdarkv2-main/resources/js/Components/Modals/InviteCollaboratorsModal.vue
<script setup>
import { VueFinalModal } from 'vue-final-modal';
import { $t } from '@/i18n.js';
import { router } from '@inertiajs/vue3';
import { defineAsyncComponent } from 'vue';
const CollaboratorCard = defineAsyncComponent(() => import('@/Components/Cards/CollaboratorCard.vue'));

const props = defineProps({
    playlist_uuid: {
        type: String,
        required: true,
    },
    following: {
        type: Array,
        default: [],
    },
});

const emit = defineEmits(['close']);

const submit = (user) => {
    router.post(
        route('playlists.collaborators.store', {
            playlist: props.playlist_uuid,
        }),
        {
            collaborator_uuid: user.uuid,
        },
    );
};
</script>

<template>
    <VueFinalModal
        class="container-fluid"
        content-class="bg-default position-absolute top-50 start-50 translate-middle rounded-4 d-flex flex-column p-4"
        content-transition="vfm-fade"
        overlay-transition="vfm-fade"
        modal-id="invite-collab-modal"
    >
        <div class="text-center font-default fs-5 mb-3">
            {{ $t('modals.invite_collaborators.title') }}
        </div>
        <div class="row w-100 playlist-container overflow-y-auto">
            <CollaboratorCard v-for="user in following" :user="user" :playlist_uuid="playlist_uuid" @invited="submit" />
        </div>
    </VueFinalModal>
</template>

<style scoped></style>
